/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  AtkObject *atko;
  GtkWidget *fixed1;
  GtkWidget *image8;
  GtkWidget *image7;
  GtkWidget *image25;
  GtkWidget *label111;
  GtkWidget *label112;
  GtkWidget *image26;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *hseparator3;
  GtkWidget *notebook3;
  GtkWidget *fixed3;
  GtkWidget *entrynom1;
  GtkWidget *entryprenom1;
  GtkWidget *entryid1;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *vseparator4;
  GtkWidget *image2;
  GtkWidget *label130;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *buttonenregistrer;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label106;
  GtkWidget *ros;
  GtkWidget *oui1;
  GSList *oui1_group = NULL;
  GtkWidget *non1;
  GtkWidget *image10;
  GtkWidget *combospe;
  GList *combospe_items = NULL;
  GtkWidget *combo_entry9;
  GtkWidget *label22;
  GtkWidget *fixed4;
  GtkWidget *treeview3;
  GtkWidget *actualiser;
  GtkWidget *vseparator7;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *label38;
  GtkWidget *modifier;
  GtkWidget *image9;
  GtkWidget *notebook6;
  GtkWidget *fixed15;
  GtkWidget *label138;
  GtkWidget *label139;
  GtkWidget *entryid2;
  GtkWidget *entrynom2;
  GtkWidget *label140;
  GtkWidget *label144;
  GtkWidget *label147;
  GtkWidget *label146;
  GtkWidget *label145;
  GtkWidget *entryprenom2;
  GtkObject *coursmodifier_adj;
  GtkWidget *coursmodifier;
  GtkWidget *non22;
  GSList *non22_group = NULL;
  GtkWidget *oui22;
  GtkWidget *vseparator8;
  GtkWidget *button24;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image28;
  GtkWidget *label148;
  GtkWidget *label137;
  GtkWidget *combo9;
  GList *combo9_items = NULL;
  GtkWidget *entry22;
  GtkWidget *label149;
  GtkWidget *fixed16;
  GtkWidget *label150;
  GtkWidget *checkbutton11;
  GtkWidget *checkbutton12;
  GtkWidget *checkbutton10;
  GtkWidget *checkbutton13;
  GtkWidget *textview4;
  GtkWidget *label152;
  GtkWidget *checkbutton9;
  GtkWidget *ressupp;
  GtkWidget *vseparator9;
  GtkWidget *supprimer;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image29;
  GtkWidget *label154;
  GtkWidget *label153;
  GtkWidget *fixed17;
  GtkWidget *label155;
  GtkWidget *vseparator10;
  GtkWidget *treeview8;
  GtkWidget *oui33;
  GSList *oui33_group = NULL;
  GtkWidget *label156;
  GtkWidget *rechercher;
  GtkWidget *non33;
  GtkWidget *tous33;
  GtkWidget *comborechercher;
  GList *comborechercher_items = NULL;
  GtkWidget *entry23;
  GtkWidget *label157;
  GtkWidget *hseparator4;
  GtkWidget *label23;
  GtkWidget *label20;
  GtkWidget *fixed12;
  GtkWidget *notebook5;
  GtkWidget *fixed13;
  GtkObject *spin66_adj;
  GtkWidget *spin66;
  GtkWidget *treeview00;
  GtkWidget *vseparator5;
  GtkWidget *label96;
  GtkWidget *label91;
  GtkWidget *label99;
  GtkWidget *label97;
  GtkWidget *image21;
  GtkWidget *gammacurve1;
  GtkWidget *label95;
  GtkWidget *type1;
  GSList *type1_group = NULL;
  GtkWidget *image18;
  GtkWidget *type2;
  GtkWidget *label93;
  GtkWidget *type3;
  GtkWidget *image19;
  GtkWidget *label98;
  GtkWidget *ajouter_salle;
  GtkWidget *verifier_salle;
  GtkWidget *verifier_materiel;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image30;
  GtkWidget *label158;
  GtkWidget *ajouter_materiel;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image14;
  GtkWidget *label116;
  GtkWidget *combocours;
  GList *combocours_items = NULL;
  GtkWidget *combo_entry4;
  GtkWidget *confirmer_cours;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image17;
  GtkWidget *label119;
  GtkWidget *confirmation_label;
  GtkWidget *ressalle;
  GtkWidget *show;
  GtkWidget *image31;
  GtkWidget *resmat;
  GtkWidget *combo01;
  GList *combo01_items = NULL;
  GtkWidget *combo_entry12;
  GtkWidget *combo02;
  GList *combo02_items = NULL;
  GtkWidget *combo_entry11;
  GtkWidget *label89;
  GtkWidget *fixed14;
  GtkWidget *treeview6;
  GtkWidget *treeview7;
  GtkWidget *combo7;
  GtkWidget *combo_entry7;
  GtkWidget *textview3;
  GtkWidget *vseparator6;
  GtkWidget *label101;
  GtkWidget *label104;
  GtkWidget *label103;
  GtkWidget *label105;
  GtkWidget *button23;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image24;
  GtkWidget *label122;
  GtkWidget *button22;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image23;
  GtkWidget *label121;
  GtkWidget *hseparator5;
  GtkWidget *button21;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image22;
  GtkWidget *label120;
  GtkWidget *combo6;
  GtkWidget *combo_entry6;
  GtkWidget *gammacurve2;
  GtkWidget *label90;
  GtkWidget *label21;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Gestion des entraineurs"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  image8 = create_pixmap (window1, "images(1).gtk");
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed1), image8, 1256, 0);
  gtk_widget_set_size_request (image8, 320, 109);

  image7 = create_pixmap (window1, "mmm.gtk");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed1), image7, 624, 0);
  gtk_widget_set_size_request (image7, 256, 112);

  image25 = gtk_image_new_from_stock ("gtk-italic", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed1), image25, 120, 24);
  gtk_widget_set_size_request (image25, 21, 21);

  label111 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>IroneCore1570@gmail.com</b></span>"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed1), label111, 144, 24);
  gtk_widget_set_size_request (label111, 208, 17);
  gtk_label_set_use_markup (GTK_LABEL (label111), TRUE);

  label112 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b> +216 7364189</b></span>"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed1), label112, 128, 48);
  gtk_widget_set_size_request (label112, 136, 17);
  gtk_label_set_use_markup (GTK_LABEL (label112), TRUE);

  image26 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed1), image26, 120, 48);
  gtk_widget_set_size_request (image26, 21, 21);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 88);
  gtk_widget_set_size_request (notebook1, 1856, 808);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed2), hseparator3, 0, 0);
  gtk_widget_set_size_request (hseparator3, 368, 16);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook3, 0, 0);
  gtk_widget_set_size_request (notebook3, 1856, 872);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed3);

  entrynom1 = gtk_entry_new ();
  gtk_widget_show (entrynom1);
  gtk_fixed_put (GTK_FIXED (fixed3), entrynom1, 200, 80);
  gtk_widget_set_size_request (entrynom1, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom1), 8226);

  entryprenom1 = gtk_entry_new ();
  gtk_widget_show (entryprenom1);
  gtk_fixed_put (GTK_FIXED (fixed3), entryprenom1, 192, 152);
  gtk_widget_set_size_request (entryprenom1, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom1), 8226);

  entryid1 = gtk_entry_new ();
  gtk_widget_show (entryid1);
  gtk_fixed_put (GTK_FIXED (fixed3), entryid1, 192, 224);
  gtk_widget_set_size_request (entryid1, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid1), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 216, 320);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label26 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>Nom :</b></span>"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed3), label26, 24, 72);
  gtk_widget_set_size_request (label26, 80, 40);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label27 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>Prenom :</b></span>"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed3), label27, 32, 144);
  gtk_widget_set_size_request (label27, 72, 33);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label28 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>ID :</b></span>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 32, 224);
  gtk_widget_set_size_request (label28, 65, 25);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  vseparator4 = gtk_vseparator_new ();
  gtk_widget_show (vseparator4);
  gtk_fixed_put (GTK_FIXED (fixed3), vseparator4, 536, 56);
  gtk_widget_set_size_request (vseparator4, 16, 368);

  image2 = create_pixmap (window1, "faza.gtk");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed3), image2, 552, 576);
  gtk_widget_set_size_request (image2, 224, 48);

  label130 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>Specialit\303\251 : </b></span>"));
  gtk_widget_show (label130);
  gtk_fixed_put (GTK_FIXED (fixed3), label130, 16, 264);
  gtk_widget_set_size_request (label130, 104, 40);
  gtk_label_set_use_markup (GTK_LABEL (label130), TRUE);

  label29 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>Nombre de cours :</b></span>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 8, 320);
  gtk_widget_set_size_request (label29, 168, 25);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label30 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>Coaching Priv\303\251  :</b></span>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed3), label30, 16, 376);
  gtk_widget_set_size_request (label30, 152, 33);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  buttonenregistrer = gtk_button_new ();
  gtk_widget_show (buttonenregistrer);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonenregistrer, 568, 584);
  gtk_widget_set_size_request (buttonenregistrer, 192, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonenregistrer), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label106 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>Enregistrer</b></span>"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (hbox1), label106, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label106), TRUE);

  ros = gtk_label_new ("");
  gtk_widget_show (ros);
  gtk_fixed_put (GTK_FIXED (fixed3), ros, 440, 640);
  gtk_widget_set_size_request (ros, 520, 48);

  oui1 = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (oui1);
  gtk_fixed_put (GTK_FIXED (fixed3), oui1, 184, 384);
  gtk_widget_set_size_request (oui1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (oui1), oui1_group);
  oui1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (oui1));

  non1 = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (non1);
  gtk_fixed_put (GTK_FIXED (fixed3), non1, 184, 416);
  gtk_widget_set_size_request (non1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (non1), oui1_group);
  oui1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (non1));

  image10 = create_pixmap (window1, "rfvg.gtk");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed3), image10, 224, 0);
  gtk_widget_set_size_request (image10, 1264, 544);

  combospe = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combospe)->popwin),
                     "GladeParentKey", combospe);
  gtk_widget_show (combospe);
  gtk_fixed_put (GTK_FIXED (fixed3), combospe, 176, 280);
  gtk_widget_set_size_request (combospe, 152, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combospe), TRUE);
  combospe_items = g_list_append (combospe_items, (gpointer) _("boxe"));
  combospe_items = g_list_append (combospe_items, (gpointer) _("fitness general"));
  combospe_items = g_list_append (combospe_items, (gpointer) _("yoga"));
  combospe_items = g_list_append (combospe_items, (gpointer) _("pilates "));
  combospe_items = g_list_append (combospe_items, (gpointer) _("Pr\303\251paration Physique"));
  combospe_items = g_list_append (combospe_items, (gpointer) _("Musculation"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combospe), combospe_items);
  g_list_free (combospe_items);

  combo_entry9 = GTK_COMBO (combospe)->entry;
  gtk_widget_show (combo_entry9);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry9), 8226);

  label22 = gtk_label_new (_("<span foreground=\"Blue\" size=\"10000\"><b>ajouter</b></span>\n"));
  gtk_widget_show (label22);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label22);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed4);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview3, 120, 104);
  gtk_widget_set_size_request (treeview3, 672, 192);

  actualiser = gtk_button_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed4), actualiser, 336, 304);
  gtk_widget_set_size_request (actualiser, 104, 21);

  vseparator7 = gtk_vseparator_new ();
  gtk_widget_show (vseparator7);
  gtk_fixed_put (GTK_FIXED (fixed4), vseparator7, 152, 368);
  gtk_widget_set_size_request (vseparator7, 16, 208);

  label107 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>Les Coachs :</b></span>"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed4), label107, 16, 56);
  gtk_widget_set_size_request (label107, 112, 33);
  gtk_label_set_use_markup (GTK_LABEL (label107), TRUE);

  label108 = gtk_label_new (_("<span foreground=\"grey\" size=\"9000\"><b>Modifier les informations du coach s\303\251lectionn\303\251 .</b></span>"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed4), label108, 208, 56);
  gtk_widget_set_size_request (label108, 312, 16);
  gtk_label_set_use_markup (GTK_LABEL (label108), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label108), 0.56, 0.5);

  label38 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>Modifier :</b></span>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed4), label38, 0, 296);
  gtk_widget_set_size_request (label38, 216, 40);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  modifier = gtk_label_new ("");
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), modifier, 952, 584);
  gtk_widget_set_size_request (modifier, 232, 96);

  image9 = create_pixmap (window1, "hhh.gtk");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed4), image9, 984, 0);
  gtk_widget_set_size_request (image9, 608, 560);

  notebook6 = gtk_notebook_new ();
  gtk_widget_show (notebook6);
  gtk_fixed_put (GTK_FIXED (fixed4), notebook6, 168, 344);
  gtk_widget_set_size_request (notebook6, 776, 328);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed15);

  label138 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>Modifier :</b></span>"));
  gtk_widget_show (label138);
  gtk_fixed_put (GTK_FIXED (fixed15), label138, 8, 8);
  gtk_widget_set_size_request (label138, 104, 33);
  gtk_label_set_use_markup (GTK_LABEL (label138), TRUE);

  label139 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>Id : </b></span>"));
  gtk_widget_show (label139);
  gtk_fixed_put (GTK_FIXED (fixed15), label139, 72, 72);
  gtk_widget_set_size_request (label139, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label139), TRUE);

  entryid2 = gtk_entry_new ();
  gtk_widget_show (entryid2);
  gtk_fixed_put (GTK_FIXED (fixed15), entryid2, 184, 64);
  gtk_widget_set_size_request (entryid2, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid2), 8226);

  entrynom2 = gtk_entry_new ();
  gtk_widget_show (entrynom2);
  gtk_fixed_put (GTK_FIXED (fixed15), entrynom2, 184, 112);
  gtk_widget_set_size_request (entrynom2, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom2), 8226);

  label140 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>Nom : </b></span>"));
  gtk_widget_show (label140);
  gtk_fixed_put (GTK_FIXED (fixed15), label140, 72, 112);
  gtk_widget_set_size_request (label140, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label140), TRUE);

  label144 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>Prenom : </b></span>"));
  gtk_widget_show (label144);
  gtk_fixed_put (GTK_FIXED (fixed15), label144, 72, 152);
  gtk_widget_set_size_request (label144, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label144), TRUE);

  label147 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>coaching : </b></span>"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed15), label147, 64, 256);
  gtk_widget_set_size_request (label147, 72, 17);
  gtk_label_set_use_markup (GTK_LABEL (label147), TRUE);

  label146 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>nbr de cours : </b></span>"));
  gtk_widget_show (label146);
  gtk_fixed_put (GTK_FIXED (fixed15), label146, 56, 224);
  gtk_widget_set_size_request (label146, 104, 17);
  gtk_label_set_use_markup (GTK_LABEL (label146), TRUE);

  label145 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>specialit\303\251: </b></span>"));
  gtk_widget_show (label145);
  gtk_fixed_put (GTK_FIXED (fixed15), label145, 64, 192);
  gtk_widget_set_size_request (label145, 72, 17);
  gtk_label_set_use_markup (GTK_LABEL (label145), TRUE);

  entryprenom2 = gtk_entry_new ();
  gtk_widget_show (entryprenom2);
  gtk_fixed_put (GTK_FIXED (fixed15), entryprenom2, 184, 152);
  gtk_widget_set_size_request (entryprenom2, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom2), 8226);

  coursmodifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  coursmodifier = gtk_spin_button_new (GTK_ADJUSTMENT (coursmodifier_adj), 1, 0);
  gtk_widget_show (coursmodifier);
  gtk_fixed_put (GTK_FIXED (fixed15), coursmodifier, 216, 224);
  gtk_widget_set_size_request (coursmodifier, 60, 27);

  non22 = gtk_radio_button_new_with_mnemonic (NULL, _("Non"));
  gtk_widget_show (non22);
  gtk_fixed_put (GTK_FIXED (fixed15), non22, 296, 256);
  gtk_widget_set_size_request (non22, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (non22), non22_group);
  non22_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (non22));

  oui22 = gtk_radio_button_new_with_mnemonic (NULL, _("Oui"));
  gtk_widget_show (oui22);
  gtk_fixed_put (GTK_FIXED (fixed15), oui22, 152, 256);
  gtk_widget_set_size_request (oui22, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (oui22), non22_group);
  non22_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (oui22));

  vseparator8 = gtk_vseparator_new ();
  gtk_widget_show (vseparator8);
  gtk_fixed_put (GTK_FIXED (fixed15), vseparator8, 400, 64);
  gtk_widget_set_size_request (vseparator8, 16, 216);

  button24 = gtk_button_new ();
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed15), button24, 496, 176);
  gtk_widget_set_size_request (button24, 136, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button24), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image28 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox14), image28, FALSE, FALSE, 0);

  label148 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" size=\"11000\"><b>Modifier</b></span>"));
  gtk_widget_show (label148);
  gtk_box_pack_start (GTK_BOX (hbox14), label148, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label148), TRUE);

  label137 = gtk_label_new (_("<span foreground=\"grey\" size=\"9000\"><b>Modifier les informations du coach s\303\251lectionn\303\251 .</b></span>"));
  gtk_widget_show (label137);
  gtk_fixed_put (GTK_FIXED (fixed15), label137, 24, 16);
  gtk_widget_set_size_request (label137, 448, 33);
  gtk_label_set_use_markup (GTK_LABEL (label137), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label137), 0.56, 0.5);

  combo9 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo9)->popwin),
                     "GladeParentKey", combo9);
  gtk_widget_show (combo9);
  gtk_fixed_put (GTK_FIXED (fixed15), combo9, 184, 192);
  gtk_widget_set_size_request (combo9, 152, 24);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo9), TRUE);
  combo9_items = g_list_append (combo9_items, (gpointer) _("boxe"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("fitness general"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("yoga"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("pilates "));
  combo9_items = g_list_append (combo9_items, (gpointer) _("Pr\303\251paration Physique"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("Musculation"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo9), combo9_items);
  g_list_free (combo9_items);

  entry22 = GTK_COMBO (combo9)->entry;
  gtk_widget_show (entry22);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 8226);

  label149 = gtk_label_new (_("<span foreground=\"Blue\" size=\"10000\"><b>Modifier</b></span>"));
  gtk_widget_show (label149);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 0), label149);
  gtk_label_set_use_markup (GTK_LABEL (label149), TRUE);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed16);

  label150 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>Raisons :</b></span>"));
  gtk_widget_show (label150);
  gtk_fixed_put (GTK_FIXED (fixed16), label150, 24, 24);
  gtk_widget_set_size_request (label150, 96, 17);
  gtk_label_set_use_markup (GTK_LABEL (label150), TRUE);

  checkbutton11 = gtk_check_button_new_with_mnemonic (_("checkbutton11"));
  gtk_widget_show (checkbutton11);
  gtk_fixed_put (GTK_FIXED (fixed16), checkbutton11, 128, 72);
  gtk_widget_set_size_request (checkbutton11, 126, 24);

  checkbutton12 = gtk_check_button_new_with_mnemonic (_("checkbutton12"));
  gtk_widget_show (checkbutton12);
  gtk_fixed_put (GTK_FIXED (fixed16), checkbutton12, 128, 96);
  gtk_widget_set_size_request (checkbutton12, 126, 24);

  checkbutton10 = gtk_check_button_new_with_mnemonic (_("checkbutton10"));
  gtk_widget_show (checkbutton10);
  gtk_fixed_put (GTK_FIXED (fixed16), checkbutton10, 128, 48);
  gtk_widget_set_size_request (checkbutton10, 126, 24);

  checkbutton13 = gtk_check_button_new_with_mnemonic (_("checkbutton13"));
  gtk_widget_show (checkbutton13);
  gtk_fixed_put (GTK_FIXED (fixed16), checkbutton13, 128, 120);
  gtk_widget_set_size_request (checkbutton13, 126, 24);

  textview4 = gtk_text_view_new ();
  gtk_widget_show (textview4);
  gtk_fixed_put (GTK_FIXED (fixed16), textview4, 40, 160);
  gtk_widget_set_size_request (textview4, 416, 128);

  label152 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>description :</b></span>"));
  gtk_widget_show (label152);
  gtk_fixed_put (GTK_FIXED (fixed16), label152, 24, 136);
  gtk_widget_set_size_request (label152, 104, 17);
  gtk_label_set_use_markup (GTK_LABEL (label152), TRUE);

  checkbutton9 = gtk_check_button_new_with_mnemonic (_("checkbutton9"));
  gtk_widget_show (checkbutton9);
  gtk_fixed_put (GTK_FIXED (fixed16), checkbutton9, 128, 24);
  gtk_widget_set_size_request (checkbutton9, 118, 24);

  ressupp = gtk_label_new ("");
  gtk_widget_show (ressupp);
  gtk_fixed_put (GTK_FIXED (fixed16), ressupp, 512, 248);
  gtk_widget_set_size_request (ressupp, 248, 33);

  vseparator9 = gtk_vseparator_new ();
  gtk_widget_show (vseparator9);
  gtk_fixed_put (GTK_FIXED (fixed16), vseparator9, 288, 16);
  gtk_widget_set_size_request (vseparator9, 32, 120);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed16), supprimer, 344, 72);
  gtk_widget_set_size_request (supprimer, 176, 37);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image29 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox15), image29, FALSE, FALSE, 0);

  label154 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label154);
  gtk_box_pack_start (GTK_BOX (hbox15), label154, FALSE, FALSE, 0);

  label153 = gtk_label_new (_("<span foreground=\"Blue\" size=\"10000\"><b>Supprimer</b></span>"));
  gtk_widget_show (label153);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 1), label153);
  gtk_label_set_use_markup (GTK_LABEL (label153), TRUE);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed17);

  label155 = gtk_label_new (_("label155"));
  gtk_widget_show (label155);
  gtk_fixed_put (GTK_FIXED (fixed17), label155, 0, 24);
  gtk_widget_set_size_request (label155, 136, 16);

  vseparator10 = gtk_vseparator_new ();
  gtk_widget_show (vseparator10);
  gtk_fixed_put (GTK_FIXED (fixed17), vseparator10, 296, 8);
  gtk_widget_set_size_request (vseparator10, 16, 280);

  treeview8 = gtk_tree_view_new ();
  gtk_widget_show (treeview8);
  gtk_fixed_put (GTK_FIXED (fixed17), treeview8, 392, 40);
  gtk_widget_set_size_request (treeview8, 300, 200);

  oui33 = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (oui33);
  gtk_fixed_put (GTK_FIXED (fixed17), oui33, 128, 88);
  gtk_widget_set_size_request (oui33, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (oui33), oui33_group);
  oui33_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (oui33));

  label156 = gtk_label_new (_("label156"));
  gtk_widget_show (label156);
  gtk_fixed_put (GTK_FIXED (fixed17), label156, 40, 88);
  gtk_widget_set_size_request (label156, 57, 17);

  rechercher = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (rechercher);
  gtk_fixed_put (GTK_FIXED (fixed17), rechercher, 72, 208);
  gtk_widget_set_size_request (rechercher, 120, 29);

  non33 = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (non33);
  gtk_fixed_put (GTK_FIXED (fixed17), non33, 128, 112);
  gtk_widget_set_size_request (non33, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (non33), oui33_group);
  oui33_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (non33));

  tous33 = gtk_radio_button_new_with_mnemonic (NULL, _("tous"));
  gtk_widget_show (tous33);
  gtk_fixed_put (GTK_FIXED (fixed17), tous33, 128, 136);
  gtk_widget_set_size_request (tous33, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (tous33), oui33_group);
  oui33_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (tous33));

  comborechercher = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (comborechercher)->popwin),
                     "GladeParentKey", comborechercher);
  gtk_widget_show (comborechercher);
  gtk_fixed_put (GTK_FIXED (fixed17), comborechercher, 152, 24);
  gtk_widget_set_size_request (comborechercher, 136, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (comborechercher), TRUE);
  comborechercher_items = g_list_append (comborechercher_items, (gpointer) _("boxe"));
  comborechercher_items = g_list_append (comborechercher_items, (gpointer) _("fitness general"));
  comborechercher_items = g_list_append (comborechercher_items, (gpointer) _("yoga"));
  comborechercher_items = g_list_append (comborechercher_items, (gpointer) _("pilates "));
  comborechercher_items = g_list_append (comborechercher_items, (gpointer) _("Pr\303\251paration Physique"));
  comborechercher_items = g_list_append (comborechercher_items, (gpointer) _("Musculation"));
  gtk_combo_set_popdown_strings (GTK_COMBO (comborechercher), comborechercher_items);
  g_list_free (comborechercher_items);

  entry23 = GTK_COMBO (comborechercher)->entry;
  gtk_widget_show (entry23);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry23), 8226);

  label157 = gtk_label_new (_("<span foreground=\"Blue\" size=\"10000\"><b>Rechercher</b></span>"));
  gtk_widget_show (label157);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 2), label157);
  gtk_label_set_use_markup (GTK_LABEL (label157), TRUE);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_fixed_put (GTK_FIXED (fixed4), hseparator4, 8, 328);
  gtk_widget_set_size_request (hseparator4, 1072, 16);

  label23 = gtk_label_new (_("<span foreground=\"Blue\" size=\"10000\"><b>Autres</b></span>"));
  gtk_widget_show (label23);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label23);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label20 = gtk_label_new (_("<span foreground=\"Blue\" size=\"10000\"><b>Admin</b></span>"));
  gtk_widget_show (label20);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label20);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12);

  notebook5 = gtk_notebook_new ();
  gtk_widget_show (notebook5);
  gtk_fixed_put (GTK_FIXED (fixed12), notebook5, 0, 0);
  gtk_widget_set_size_request (notebook5, 1848, 872);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook5), fixed13);

  spin66_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spin66 = gtk_spin_button_new (GTK_ADJUSTMENT (spin66_adj), 1, 0);
  gtk_widget_show (spin66);
  gtk_fixed_put (GTK_FIXED (fixed13), spin66, 280, 304);
  gtk_widget_set_size_request (spin66, 60, 27);

  treeview00 = gtk_tree_view_new ();
  gtk_widget_show (treeview00);
  gtk_fixed_put (GTK_FIXED (fixed13), treeview00, 688, 312);
  gtk_widget_set_size_request (treeview00, 408, 192);

  vseparator5 = gtk_vseparator_new ();
  gtk_widget_show (vseparator5);
  gtk_fixed_put (GTK_FIXED (fixed13), vseparator5, 648, 80);
  gtk_widget_set_size_request (vseparator5, 24, 464);

  label96 = gtk_label_new (_("<span foreground=\"black\" size=\"13500\"><b>Reservation</b></span>"));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed13), label96, 800, 88);
  gtk_widget_set_size_request (label96, 232, 23);
  gtk_label_set_use_markup (GTK_LABEL (label96), TRUE);

  label91 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>Mes cours :</b></span>"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed13), label91, 16, 176);
  gtk_widget_set_size_request (label91, 128, 39);
  gtk_label_set_use_markup (GTK_LABEL (label91), TRUE);

  label99 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>Type :</b></span>"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed13), label99, 0, 232);
  gtk_widget_set_size_request (label99, 152, 25);
  gtk_label_set_use_markup (GTK_LABEL (label99), TRUE);

  label97 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>Matriel a utiliser :</b></span>"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed13), label97, 664, 176);
  gtk_widget_set_size_request (label97, 144, 17);
  gtk_label_set_use_markup (GTK_LABEL (label97), TRUE);

  image21 = create_pixmap (window1, "20.gtk");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed13), image21, 1072, 0);
  gtk_widget_set_size_request (image21, 512, 176);

  gammacurve1 = gtk_gamma_curve_new ();
  gtk_widget_show (gammacurve1);
  gtk_fixed_put (GTK_FIXED (fixed13), gammacurve1, 56, 480);
  gtk_widget_set_size_request (gammacurve1, 344, 168);
  gtk_curve_set_range (GTK_CURVE (GTK_GAMMA_CURVE (gammacurve1)->curve), 0, 1, 0, 1);

  label95 = gtk_label_new (_("<span foreground=\"black\" size=\"13500\"><b>Inscription a un cours</b></span>"));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed13), label95, 88, 72);
  gtk_widget_set_size_request (label95, 312, 32);
  gtk_label_set_use_markup (GTK_LABEL (label95), TRUE);

  type1 = gtk_radio_button_new_with_mnemonic (NULL, _("coaching priv\303\251e"));
  gtk_widget_show (type1);
  gtk_fixed_put (GTK_FIXED (fixed13), type1, 104, 240);
  gtk_widget_set_size_request (type1, 144, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (type1), type1_group);
  type1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (type1));

  image18 = create_pixmap (window1, "jefv.gtk");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed13), image18, 256, 128);
  gtk_widget_set_size_request (image18, 408, 312);

  type2 = gtk_radio_button_new_with_mnemonic (NULL, _("en groupe"));
  gtk_widget_show (type2);
  gtk_fixed_put (GTK_FIXED (fixed13), type2, 104, 256);
  gtk_widget_set_size_request (type2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (type2), type1_group);
  type1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (type2));

  label93 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>Nombre de participant :</b></span>"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed13), label93, 32, 304);
  gtk_widget_set_size_request (label93, 160, 32);
  gtk_label_set_use_markup (GTK_LABEL (label93), TRUE);

  type3 = gtk_radio_button_new_with_mnemonic (NULL, _("tous"));
  gtk_widget_show (type3);
  gtk_fixed_put (GTK_FIXED (fixed13), type3, 104, 280);
  gtk_widget_set_size_request (type3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (type3), type1_group);
  type1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (type3));

  image19 = create_pixmap (window1, "faza.gtk");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed13), image19, 536, 616);
  gtk_widget_set_size_request (image19, 384, 56);

  label98 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>Salle  :</b></span>"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed13), label98, 672, 248);
  gtk_widget_set_size_request (label98, 104, 17);
  gtk_label_set_use_markup (GTK_LABEL (label98), TRUE);

  ajouter_salle = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (ajouter_salle);
  gtk_fixed_put (GTK_FIXED (fixed13), ajouter_salle, 1200, 256);
  gtk_widget_set_size_request (ajouter_salle, 74, 29);

  verifier_salle = gtk_button_new_with_mnemonic (_("verifier"));
  gtk_widget_show (verifier_salle);
  gtk_fixed_put (GTK_FIXED (fixed13), verifier_salle, 1104, 256);
  gtk_widget_set_size_request (verifier_salle, 74, 29);

  verifier_materiel = gtk_button_new ();
  gtk_widget_show (verifier_materiel);
  gtk_fixed_put (GTK_FIXED (fixed13), verifier_materiel, 1016, 192);
  gtk_widget_set_size_request (verifier_materiel, 88, 24);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (verifier_materiel), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image30 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox16), image30, FALSE, FALSE, 0);

  label158 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\" size=\"11000\"><b>Verifier</b></span>"));
  gtk_widget_show (label158);
  gtk_box_pack_start (GTK_BOX (hbox16), label158, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label158), TRUE);

  ajouter_materiel = gtk_button_new ();
  gtk_widget_show (ajouter_materiel);
  gtk_fixed_put (GTK_FIXED (fixed13), ajouter_materiel, 1120, 192);
  gtk_widget_set_size_request (ajouter_materiel, 88, 24);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ajouter_materiel), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox7), image14, FALSE, FALSE, 0);

  label116 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\" size=\"11000\"><b>Ajouter</b></span>"));
  gtk_widget_show (label116);
  gtk_box_pack_start (GTK_BOX (hbox7), label116, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label116), TRUE);

  combocours = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combocours)->popwin),
                     "GladeParentKey", combocours);
  gtk_widget_show (combocours);
  gtk_fixed_put (GTK_FIXED (fixed13), combocours, 224, 176);
  gtk_widget_set_size_request (combocours, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combocours), TRUE);
  combocours_items = g_list_append (combocours_items, (gpointer) _("Cardio"));
  combocours_items = g_list_append (combocours_items, (gpointer) _("Musculation"));
  combocours_items = g_list_append (combocours_items, (gpointer) _("Yoga"));
  combocours_items = g_list_append (combocours_items, (gpointer) _("Mixte"));
  combocours_items = g_list_append (combocours_items, (gpointer) _("Boxe"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combocours), combocours_items);
  g_list_free (combocours_items);

  combo_entry4 = GTK_COMBO (combocours)->entry;
  gtk_widget_show (combo_entry4);
  gtk_entry_set_text (GTK_ENTRY (combo_entry4), _("Cardio"));
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry4), 8226);

  confirmer_cours = gtk_button_new ();
  gtk_widget_show (confirmer_cours);
  gtk_fixed_put (GTK_FIXED (fixed13), confirmer_cours, 600, 624);
  gtk_widget_set_size_request (confirmer_cours, 256, 37);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (confirmer_cours), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image17 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox10), image17, FALSE, FALSE, 0);

  label119 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" size=\"11000\"><b>Confirmer</b></span>"));
  gtk_widget_show (label119);
  gtk_box_pack_start (GTK_BOX (hbox10), label119, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label119), TRUE);

  confirmation_label = gtk_label_new ("");
  gtk_widget_show (confirmation_label);
  gtk_fixed_put (GTK_FIXED (fixed13), confirmation_label, 1152, 568);
  gtk_widget_set_size_request (confirmation_label, 240, 49);

  ressalle = gtk_label_new ("");
  gtk_widget_show (ressalle);
  gtk_fixed_put (GTK_FIXED (fixed13), ressalle, 1152, 528);
  gtk_widget_set_size_request (ressalle, 280, 33);

  show = gtk_button_new ();
  gtk_widget_show (show);
  gtk_fixed_put (GTK_FIXED (fixed13), show, 1112, 336);
  gtk_widget_set_size_request (show, 88, 24);

  image31 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_container_add (GTK_CONTAINER (show), image31);

  resmat = gtk_label_new ("");
  gtk_widget_show (resmat);
  gtk_fixed_put (GTK_FIXED (fixed13), resmat, 1152, 480);
  gtk_widget_set_size_request (resmat, 256, 41);

  combo01 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo01)->popwin),
                     "GladeParentKey", combo01);
  gtk_widget_show (combo01);
  gtk_fixed_put (GTK_FIXED (fixed13), combo01, 832, 184);
  gtk_widget_set_size_request (combo01, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo01), TRUE);
  combo01_items = g_list_append (combo01_items, (gpointer) _("Ballon de football"));
  combo01_items = g_list_append (combo01_items, (gpointer) _("Tapis de yoga"));
  combo01_items = g_list_append (combo01_items, (gpointer) _("Halt\303\250res 5kg"));
  combo01_items = g_list_append (combo01_items, (gpointer) _("Corde \303\240 sauter"));
  combo01_items = g_list_append (combo01_items, (gpointer) _("Ballon m\303\251decine"));
  combo01_items = g_list_append (combo01_items, (gpointer) _("Barre de traction"));
  combo01_items = g_list_append (combo01_items, (gpointer) _("Banc de musculation"));
  combo01_items = g_list_append (combo01_items, (gpointer) _("V\303\251lo d'appartemen"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo01), combo01_items);
  g_list_free (combo01_items);

  combo_entry12 = GTK_COMBO (combo01)->entry;
  gtk_widget_show (combo_entry12);
  gtk_entry_set_text (GTK_ENTRY (combo_entry12), _("Ballon de football"));
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry12), 8226);

  combo02 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo02)->popwin),
                     "GladeParentKey", combo02);
  gtk_widget_show (combo02);
  gtk_fixed_put (GTK_FIXED (fixed13), combo02, 808, 240);
  gtk_widget_set_size_request (combo02, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo02), TRUE);
  combo02_items = g_list_append (combo02_items, (gpointer) _("Salle A"));
  combo02_items = g_list_append (combo02_items, (gpointer) _("Salle B"));
  combo02_items = g_list_append (combo02_items, (gpointer) _("Salle C"));
  combo02_items = g_list_append (combo02_items, (gpointer) _("Salle D"));
  combo02_items = g_list_append (combo02_items, (gpointer) _("Salle E"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo02), combo02_items);
  g_list_free (combo02_items);

  combo_entry11 = GTK_COMBO (combo02)->entry;
  gtk_widget_show (combo_entry11);
  gtk_entry_set_text (GTK_ENTRY (combo_entry11), _("Salle A"));
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry11), 8226);

  label89 = gtk_label_new (_("<span foreground=\"Blue\" size=\"10000\"><b>Cours</b></span>"));
  gtk_widget_show (label89);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 0), label89);
  gtk_label_set_use_markup (GTK_LABEL (label89), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label89), 0.47, 0.5);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook5), fixed14);

  treeview6 = gtk_tree_view_new ();
  gtk_widget_show (treeview6);
  gtk_fixed_put (GTK_FIXED (fixed14), treeview6, 904, 224);
  gtk_widget_set_size_request (treeview6, 328, 136);

  treeview7 = gtk_tree_view_new ();
  gtk_widget_show (treeview7);
  gtk_fixed_put (GTK_FIXED (fixed14), treeview7, 168, 552);
  gtk_widget_set_size_request (treeview7, 312, 152);

  combo7 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo7)->popwin),
                     "GladeParentKey", combo7);
  gtk_widget_show (combo7);
  gtk_fixed_put (GTK_FIXED (fixed14), combo7, 176, 472);
  gtk_widget_set_size_request (combo7, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo7), TRUE);

  combo_entry7 = GTK_COMBO (combo7)->entry;
  gtk_widget_show (combo_entry7);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry7), 8226);

  textview3 = gtk_text_view_new ();
  gtk_widget_show (textview3);
  gtk_fixed_put (GTK_FIXED (fixed14), textview3, 888, 480);
  gtk_widget_set_size_request (textview3, 456, 208);

  vseparator6 = gtk_vseparator_new ();
  gtk_widget_show (vseparator6);
  gtk_fixed_put (GTK_FIXED (fixed14), vseparator6, 736, 80);
  gtk_widget_set_size_request (vseparator6, 24, 696);

  label101 = gtk_label_new (_("<span foreground=\"black\" size=\"13500\"><b>Coaching priv\303\251 :</b></span>"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed14), label101, 208, 72);
  gtk_widget_set_size_request (label101, 176, 33);
  gtk_label_set_use_markup (GTK_LABEL (label101), TRUE);

  label104 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>ID Adherent :</b></span>"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed14), label104, 32, 448);
  gtk_widget_set_size_request (label104, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label104), TRUE);

  label103 = gtk_label_new (_("<span foreground=\"black\" size=\"11000\"><b>Cours :</b></span>"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed14), label103, 776, 137);
  gtk_widget_set_size_request (label103, 72, 16);
  gtk_label_set_use_markup (GTK_LABEL (label103), TRUE);

  label105 = gtk_label_new (_("<span foreground=\"black\" size=\"12500\"><b>Reclamation :</b></span>"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed14), label105, 792, 440);
  gtk_widget_set_size_request (label105, 112, 25);
  gtk_label_set_use_markup (GTK_LABEL (label105), TRUE);

  button23 = gtk_button_new ();
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed14), button23, 1280, 696);
  gtk_widget_set_size_request (button23, 96, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button23), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image24 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox13), image24, FALSE, FALSE, 0);

  label122 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\" size=\"11000\"><b>Envoyer</b></span>"));
  gtk_widget_show (label122);
  gtk_box_pack_start (GTK_BOX (hbox13), label122, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label122), TRUE);

  button22 = gtk_button_new ();
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed14), button22, 1224, 136);
  gtk_widget_set_size_request (button22, 112, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button22), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image23 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox12), image23, FALSE, FALSE, 0);

  label121 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\" size=\"11000\"><b>Afficher</b></span>"));
  gtk_widget_show (label121);
  gtk_box_pack_start (GTK_BOX (hbox12), label121, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label121), TRUE);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_fixed_put (GTK_FIXED (fixed14), hseparator5, 752, 408);
  gtk_widget_set_size_request (hseparator5, 656, 16);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed14), button21, 408, 464);
  gtk_widget_set_size_request (button21, 112, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button21), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image22 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox11), image22, FALSE, FALSE, 0);

  label120 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\" size=\"11000\"><b>Afficher</b></span>"));
  gtk_widget_show (label120);
  gtk_box_pack_start (GTK_BOX (hbox11), label120, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label120), TRUE);

  combo6 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo6)->popwin),
                     "GladeParentKey", combo6);
  gtk_widget_show (combo6);
  gtk_fixed_put (GTK_FIXED (fixed14), combo6, 944, 136);
  gtk_widget_set_size_request (combo6, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo6), TRUE);

  combo_entry6 = GTK_COMBO (combo6)->entry;
  gtk_widget_show (combo_entry6);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry6), 8226);

  gammacurve2 = gtk_gamma_curve_new ();
  gtk_widget_show (gammacurve2);
  gtk_fixed_put (GTK_FIXED (fixed14), gammacurve2, 128, 144);
  gtk_widget_set_size_request (gammacurve2, 392, 256);
  gtk_curve_set_range (GTK_CURVE (GTK_GAMMA_CURVE (gammacurve2)->curve), 0, 1, 0, 1);

  label90 = gtk_label_new (_("<span foreground=\"Blue\" size=\"10000\"><b>Performance</b></span>"));
  gtk_widget_show (label90);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 1), label90);
  gtk_label_set_use_markup (GTK_LABEL (label90), TRUE);

  label21 = gtk_label_new (_("<span foreground=\"Blue\" size=\"10000\"><b>Entraineur</b></span>"));
  gtk_widget_show (label21);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label21);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  g_signal_connect ((gpointer) buttonenregistrer, "clicked",
                    G_CALLBACK (on_buttonenregistrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) oui1, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) non1, "toggled",
                    G_CALLBACK (on_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) treeview3, "row_activated",
                    G_CALLBACK (on_treeview3_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview3, "cursor_changed",
                    G_CALLBACK (on_treeview3_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24, "clicked",
                    G_CALLBACK (on_buttonmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview8, "cursor_changed",
                    G_CALLBACK (on_treeview8_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) rechercher, "clicked",
                    G_CALLBACK (on_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_salle, "clicked",
                    G_CALLBACK (on_ajouter_salle_clicked),
                    NULL);
  g_signal_connect ((gpointer) verifier_salle, "clicked",
                    G_CALLBACK (on_verifier_salle_clicked),
                    NULL);
  g_signal_connect ((gpointer) verifier_materiel, "clicked",
                    G_CALLBACK (on_verifier_materiel_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_materiel, "clicked",
                    G_CALLBACK (on_ajouter_materiel_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmer_cours, "clicked",
                    G_CALLBACK (on_confirmer_cours_clicked),
                    NULL);
  g_signal_connect ((gpointer) show, "clicked",
                    G_CALLBACK (on_show_clicked),
                    NULL);

  atko = gtk_widget_get_accessible (window1);
  atk_object_set_name (atko, _("Gestion des entraineurs"));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, image25, "image25");
  GLADE_HOOKUP_OBJECT (window1, label111, "label111");
  GLADE_HOOKUP_OBJECT (window1, label112, "label112");
  GLADE_HOOKUP_OBJECT (window1, image26, "image26");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (window1, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, entrynom1, "entrynom1");
  GLADE_HOOKUP_OBJECT (window1, entryprenom1, "entryprenom1");
  GLADE_HOOKUP_OBJECT (window1, entryid1, "entryid1");
  GLADE_HOOKUP_OBJECT (window1, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, vseparator4, "vseparator4");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label130, "label130");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1, buttonenregistrer, "buttonenregistrer");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label106, "label106");
  GLADE_HOOKUP_OBJECT (window1, ros, "ros");
  GLADE_HOOKUP_OBJECT (window1, oui1, "oui1");
  GLADE_HOOKUP_OBJECT (window1, non1, "non1");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, combospe, "combospe");
  GLADE_HOOKUP_OBJECT (window1, combo_entry9, "combo_entry9");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window1, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (window1, vseparator7, "vseparator7");
  GLADE_HOOKUP_OBJECT (window1, label107, "label107");
  GLADE_HOOKUP_OBJECT (window1, label108, "label108");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, notebook6, "notebook6");
  GLADE_HOOKUP_OBJECT (window1, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (window1, label138, "label138");
  GLADE_HOOKUP_OBJECT (window1, label139, "label139");
  GLADE_HOOKUP_OBJECT (window1, entryid2, "entryid2");
  GLADE_HOOKUP_OBJECT (window1, entrynom2, "entrynom2");
  GLADE_HOOKUP_OBJECT (window1, label140, "label140");
  GLADE_HOOKUP_OBJECT (window1, label144, "label144");
  GLADE_HOOKUP_OBJECT (window1, label147, "label147");
  GLADE_HOOKUP_OBJECT (window1, label146, "label146");
  GLADE_HOOKUP_OBJECT (window1, label145, "label145");
  GLADE_HOOKUP_OBJECT (window1, entryprenom2, "entryprenom2");
  GLADE_HOOKUP_OBJECT (window1, coursmodifier, "coursmodifier");
  GLADE_HOOKUP_OBJECT (window1, non22, "non22");
  GLADE_HOOKUP_OBJECT (window1, oui22, "oui22");
  GLADE_HOOKUP_OBJECT (window1, vseparator8, "vseparator8");
  GLADE_HOOKUP_OBJECT (window1, button24, "button24");
  GLADE_HOOKUP_OBJECT (window1, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, image28, "image28");
  GLADE_HOOKUP_OBJECT (window1, label148, "label148");
  GLADE_HOOKUP_OBJECT (window1, label137, "label137");
  GLADE_HOOKUP_OBJECT (window1, combo9, "combo9");
  GLADE_HOOKUP_OBJECT (window1, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (window1, label149, "label149");
  GLADE_HOOKUP_OBJECT (window1, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (window1, label150, "label150");
  GLADE_HOOKUP_OBJECT (window1, checkbutton11, "checkbutton11");
  GLADE_HOOKUP_OBJECT (window1, checkbutton12, "checkbutton12");
  GLADE_HOOKUP_OBJECT (window1, checkbutton10, "checkbutton10");
  GLADE_HOOKUP_OBJECT (window1, checkbutton13, "checkbutton13");
  GLADE_HOOKUP_OBJECT (window1, textview4, "textview4");
  GLADE_HOOKUP_OBJECT (window1, label152, "label152");
  GLADE_HOOKUP_OBJECT (window1, checkbutton9, "checkbutton9");
  GLADE_HOOKUP_OBJECT (window1, ressupp, "ressupp");
  GLADE_HOOKUP_OBJECT (window1, vseparator9, "vseparator9");
  GLADE_HOOKUP_OBJECT (window1, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (window1, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, image29, "image29");
  GLADE_HOOKUP_OBJECT (window1, label154, "label154");
  GLADE_HOOKUP_OBJECT (window1, label153, "label153");
  GLADE_HOOKUP_OBJECT (window1, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (window1, label155, "label155");
  GLADE_HOOKUP_OBJECT (window1, vseparator10, "vseparator10");
  GLADE_HOOKUP_OBJECT (window1, treeview8, "treeview8");
  GLADE_HOOKUP_OBJECT (window1, oui33, "oui33");
  GLADE_HOOKUP_OBJECT (window1, label156, "label156");
  GLADE_HOOKUP_OBJECT (window1, rechercher, "rechercher");
  GLADE_HOOKUP_OBJECT (window1, non33, "non33");
  GLADE_HOOKUP_OBJECT (window1, tous33, "tous33");
  GLADE_HOOKUP_OBJECT (window1, comborechercher, "comborechercher");
  GLADE_HOOKUP_OBJECT (window1, entry23, "entry23");
  GLADE_HOOKUP_OBJECT (window1, label157, "label157");
  GLADE_HOOKUP_OBJECT (window1, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window1, notebook5, "notebook5");
  GLADE_HOOKUP_OBJECT (window1, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (window1, spin66, "spin66");
  GLADE_HOOKUP_OBJECT (window1, treeview00, "treeview00");
  GLADE_HOOKUP_OBJECT (window1, vseparator5, "vseparator5");
  GLADE_HOOKUP_OBJECT (window1, label96, "label96");
  GLADE_HOOKUP_OBJECT (window1, label91, "label91");
  GLADE_HOOKUP_OBJECT (window1, label99, "label99");
  GLADE_HOOKUP_OBJECT (window1, label97, "label97");
  GLADE_HOOKUP_OBJECT (window1, image21, "image21");
  GLADE_HOOKUP_OBJECT (window1, gammacurve1, "gammacurve1");
  GLADE_HOOKUP_OBJECT (window1, label95, "label95");
  GLADE_HOOKUP_OBJECT (window1, type1, "type1");
  GLADE_HOOKUP_OBJECT (window1, image18, "image18");
  GLADE_HOOKUP_OBJECT (window1, type2, "type2");
  GLADE_HOOKUP_OBJECT (window1, label93, "label93");
  GLADE_HOOKUP_OBJECT (window1, type3, "type3");
  GLADE_HOOKUP_OBJECT (window1, image19, "image19");
  GLADE_HOOKUP_OBJECT (window1, label98, "label98");
  GLADE_HOOKUP_OBJECT (window1, ajouter_salle, "ajouter_salle");
  GLADE_HOOKUP_OBJECT (window1, verifier_salle, "verifier_salle");
  GLADE_HOOKUP_OBJECT (window1, verifier_materiel, "verifier_materiel");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, image30, "image30");
  GLADE_HOOKUP_OBJECT (window1, label158, "label158");
  GLADE_HOOKUP_OBJECT (window1, ajouter_materiel, "ajouter_materiel");
  GLADE_HOOKUP_OBJECT (window1, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label116, "label116");
  GLADE_HOOKUP_OBJECT (window1, combocours, "combocours");
  GLADE_HOOKUP_OBJECT (window1, combo_entry4, "combo_entry4");
  GLADE_HOOKUP_OBJECT (window1, confirmer_cours, "confirmer_cours");
  GLADE_HOOKUP_OBJECT (window1, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, label119, "label119");
  GLADE_HOOKUP_OBJECT (window1, confirmation_label, "confirmation_label");
  GLADE_HOOKUP_OBJECT (window1, ressalle, "ressalle");
  GLADE_HOOKUP_OBJECT (window1, show, "show");
  GLADE_HOOKUP_OBJECT (window1, image31, "image31");
  GLADE_HOOKUP_OBJECT (window1, resmat, "resmat");
  GLADE_HOOKUP_OBJECT (window1, combo01, "combo01");
  GLADE_HOOKUP_OBJECT (window1, combo_entry12, "combo_entry12");
  GLADE_HOOKUP_OBJECT (window1, combo02, "combo02");
  GLADE_HOOKUP_OBJECT (window1, combo_entry11, "combo_entry11");
  GLADE_HOOKUP_OBJECT (window1, label89, "label89");
  GLADE_HOOKUP_OBJECT (window1, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (window1, treeview6, "treeview6");
  GLADE_HOOKUP_OBJECT (window1, treeview7, "treeview7");
  GLADE_HOOKUP_OBJECT (window1, combo7, "combo7");
  GLADE_HOOKUP_OBJECT (window1, combo_entry7, "combo_entry7");
  GLADE_HOOKUP_OBJECT (window1, textview3, "textview3");
  GLADE_HOOKUP_OBJECT (window1, vseparator6, "vseparator6");
  GLADE_HOOKUP_OBJECT (window1, label101, "label101");
  GLADE_HOOKUP_OBJECT (window1, label104, "label104");
  GLADE_HOOKUP_OBJECT (window1, label103, "label103");
  GLADE_HOOKUP_OBJECT (window1, label105, "label105");
  GLADE_HOOKUP_OBJECT (window1, button23, "button23");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image24, "image24");
  GLADE_HOOKUP_OBJECT (window1, label122, "label122");
  GLADE_HOOKUP_OBJECT (window1, button22, "button22");
  GLADE_HOOKUP_OBJECT (window1, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image23, "image23");
  GLADE_HOOKUP_OBJECT (window1, label121, "label121");
  GLADE_HOOKUP_OBJECT (window1, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (window1, button21, "button21");
  GLADE_HOOKUP_OBJECT (window1, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1, image22, "image22");
  GLADE_HOOKUP_OBJECT (window1, label120, "label120");
  GLADE_HOOKUP_OBJECT (window1, combo6, "combo6");
  GLADE_HOOKUP_OBJECT (window1, combo_entry6, "combo_entry6");
  GLADE_HOOKUP_OBJECT (window1, gammacurve2, "gammacurve2");
  GLADE_HOOKUP_OBJECT (window1, label90, "label90");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");

  return window1;
}

