/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *yh_window;

  // Initialisation GTK
  gtk_init (&argc, &argv);

  // Ajouter le répertoire courant pour les pixmaps
  // Simplifié: on utilise juste le répertoire courant "."
  add_pixmap_directory ("pixmaps");


  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  yh_window = create_yh_window ();
  gtk_widget_show (yh_window);

  gtk_main ();
  return 0;
}

