/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *image4;
  GtkWidget *label3;
  GtkWidget *image3;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *AjoutIDev;
  GtkWidget *AjoutNomEv;
  GtkWidget *label19;
  GtkObject *AjoutNbrInviteEv_adj;
  GtkWidget *AjoutNbrInviteEv;
  GtkWidget *label22;
  GtkWidget *label17;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label25;
  GtkWidget *hbuttonbox1;
  GtkWidget *hbuttonbox2;
  GtkWidget *label16;
  GtkObject *AjoutJourEv_adj;
  GtkWidget *AjoutJourEv;
  GtkObject *AjoutMoisEv_adj;
  GtkWidget *AjoutMoisEv;
  GtkObject *AjoutAnneeEv_adj;
  GtkWidget *AjoutAnneeEv;
  GtkWidget *lab;
  GtkWidget *label71;
  GtkWidget *jour;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *AjoutBoutonTypeEv;
  GtkWidget *AjoutPriveEv;
  GSList *AjoutPriveEv_group = NULL;
  GtkWidget *AjoutPublicEv;
  GtkWidget *AjoutTypeEv;
  GtkWidget *AjoutBoutonEv;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image5;
  GtkWidget *label41;
  GtkWidget *image15;
  GtkWidget *AfficherAjout;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image17;
  GtkWidget *label75;
  GtkWidget *label10;
  GtkWidget *fixed3;
  GtkWidget *label28;
  GtkWidget *ModifIDev;
  GtkWidget *ModifNomEv;
  GtkObject *ModifNbrInvites_adj;
  GtkWidget *ModifNbrInvites;
  GtkWidget *label34;
  GtkWidget *label33;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkObject *ModifJourEv_adj;
  GtkWidget *ModifJourEv;
  GtkObject *ModifMoisEv_adj;
  GtkWidget *ModifMoisEv;
  GtkObject *ModifAnneeEv_adj;
  GtkWidget *ModifAnneeEv;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *label74;
  GtkWidget *ModifChercher;
  GtkWidget *ModifTypeBouton;
  GtkWidget *ModifPriveEv;
  GSList *ModifPriveEv_group = NULL;
  GtkWidget *ModifPublicEv;
  GtkWidget *ModifBouton_;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image6;
  GtkWidget *label40;
  GtkWidget *ModifTypeEv;
  GtkWidget *label11;
  GtkWidget *fixed4;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *SuppDecrireEv;
  GtkWidget *label44;
  GtkWidget *SuppIDev;
  GtkWidget *SuppCheckboxEv;
  GtkWidget *SuppButton;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image18;
  GtkWidget *label76;
  GtkWidget *label12;
  GtkWidget *fixed5;
  GtkWidget *label46;
  GtkWidget *IDrecherche;
  GtkWidget *treeview;
  GtkWidget *Rechercher;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image8;
  GtkWidget *label47;
  GtkWidget *supprimerRecherche;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image10;
  GtkWidget *label55;
  GtkWidget *ActualiserRecherhce;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image9;
  GtkWidget *label54;
  GtkWidget *label13;
  GtkWidget *fixed6;
  GtkWidget *IDinscri;
  GtkWidget *nomprenomInscri;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkObject *AgeInscri_adj;
  GtkWidget *AgeInscri;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *image16;
  GtkWidget *Evenementinscrire;
  GtkWidget *FemmeInscri;
  GtkWidget *SinscrireButton;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label64;
  GtkWidget *okChoisirEventInscri;
  GtkWidget *HommeInscri;
  GtkWidget *label14;
  GtkWidget *fixed7;
  GtkWidget *StatNombreEvent;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *StatNombreInvite;
  GtkWidget *BoutonCalculer;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image13;
  GtkWidget *label67;
  GtkWidget *BoutonExporter;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image14;
  GtkWidget *label68;
  GtkWidget *label15;
  GtkWidget *image2;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Gestion des \303\251venements"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  image1 = create_pixmap (window1, "images.gtk");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 1392, 0);
  gtk_widget_set_size_request (image1, 304, 152);

  label2 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"10000\" weight=\"bold\">+216 73641189</span>"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 168, 64);
  gtk_widget_set_size_request (label2, 168, 24);
  GTK_WIDGET_SET_FLAGS (label2, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label2), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label2), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  image4 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed1), image4, 168, 64);
  gtk_widget_set_size_request (image4, 21, 21);

  label3 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"10000\" weight=\"bold\">Ironcore1570@gmail.com</span>"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 184, 32);
  gtk_widget_set_size_request (label3, 216, 24);
  GTK_WIDGET_SET_FLAGS (label3, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label3), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label3), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label3), 5, 0);

  image3 = gtk_image_new_from_stock ("gtk-italic", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed1), image3, 168, 32);
  gtk_widget_set_size_request (image3, 21, 21);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 152);
  gtk_widget_set_size_request (notebook1, 1848, 736);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  AjoutIDev = gtk_entry_new ();
  gtk_widget_show (AjoutIDev);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutIDev, 384, 96);
  gtk_widget_set_size_request (AjoutIDev, 392, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (AjoutIDev), 8226);

  AjoutNomEv = gtk_entry_new ();
  gtk_widget_show (AjoutNomEv);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutNomEv, 384, 152);
  gtk_widget_set_size_request (AjoutNomEv, 392, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (AjoutNomEv), 8226);

  label19 = gtk_label_new ("");
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed2), label19, 184, 272);
  gtk_widget_set_size_request (label19, 49, 17);

  AjoutNbrInviteEv_adj = gtk_adjustment_new (0, 1, 5000, 1, 10, 10);
  AjoutNbrInviteEv = gtk_spin_button_new (GTK_ADJUSTMENT (AjoutNbrInviteEv_adj), 1, 0);
  gtk_widget_show (AjoutNbrInviteEv);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutNbrInviteEv, 384, 280);
  gtk_widget_set_size_request (AjoutNbrInviteEv, 232, 32);

  label22 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"14000\" weight=\"bold\">Veuiller remplir le formulaire pour ajouter un \303\251venement :</span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 56, 16);
  gtk_widget_set_size_request (label22, 624, 32);
  GTK_WIDGET_SET_FLAGS (label22, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);
  gtk_label_set_justify (GTK_LABEL (label22), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label22), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label22), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label22), 5, 0);

  label17 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Donner le nom de l'\303\251venement</span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 80, 160);
  gtk_widget_set_size_request (label17, 256, 24);
  GTK_WIDGET_SET_FLAGS (label17, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label17), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label17), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label17), 5, 0);

  label20 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Type\n</span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed2), label20, 72, 216);
  gtk_widget_set_size_request (label20, 272, 16);
  GTK_WIDGET_SET_FLAGS (label20, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label20), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label20), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label20), 5, 0);

  label21 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Nombres d'invit\303\251s</span>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 128, 288);
  gtk_widget_set_size_request (label21, 168, 16);
  GTK_WIDGET_SET_FLAGS (label21, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label21), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label21), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label21), 5, 0);

  label25 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Date :</span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed2), label25, 184, 448);
  gtk_widget_set_size_request (label25, 49, 17);
  GTK_WIDGET_SET_FLAGS (label25, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);
  gtk_label_set_justify (GTK_LABEL (label25), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label25), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label25), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label25), 5, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_fixed_put (GTK_FIXED (fixed2), hbuttonbox1, 1224, 392);
  gtk_widget_set_size_request (hbuttonbox1, 85, 29);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_fixed_put (GTK_FIXED (fixed2), hbuttonbox2, 1192, 448);
  gtk_widget_set_size_request (hbuttonbox2, 85, 29);

  label16 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Donner l'ID de l'\303\251venement</span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 64, 104);
  gtk_widget_set_size_request (label16, 256, 32);
  GTK_WIDGET_SET_FLAGS (label16, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label16), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label16), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label16), 5, 0);

  AjoutJourEv_adj = gtk_adjustment_new (31, 1, 31, 1, 10, 10);
  AjoutJourEv = gtk_spin_button_new (GTK_ADJUSTMENT (AjoutJourEv_adj), 1, 0);
  gtk_widget_show (AjoutJourEv);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutJourEv, 312, 448);
  gtk_widget_set_size_request (AjoutJourEv, 60, 27);

  AjoutMoisEv_adj = gtk_adjustment_new (2, 1, 12, 1, 10, 10);
  AjoutMoisEv = gtk_spin_button_new (GTK_ADJUSTMENT (AjoutMoisEv_adj), 1, 0);
  gtk_widget_show (AjoutMoisEv);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutMoisEv, 432, 448);
  gtk_widget_set_size_request (AjoutMoisEv, 80, 27);

  AjoutAnneeEv_adj = gtk_adjustment_new (1, 1990, 2030, 1, 10, 10);
  AjoutAnneeEv = gtk_spin_button_new (GTK_ADJUSTMENT (AjoutAnneeEv_adj), 1, 0);
  gtk_widget_show (AjoutAnneeEv);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutAnneeEv, 576, 448);
  gtk_widget_set_size_request (AjoutAnneeEv, 104, 24);

  lab = gtk_label_new (_("mois"));
  gtk_widget_show (lab);
  gtk_fixed_put (GTK_FIXED (fixed2), lab, 384, 448);
  gtk_widget_set_size_request (lab, 49, 17);

  label71 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed2), label71, 520, 448);
  gtk_widget_set_size_request (label71, 49, 17);

  jour = gtk_label_new (_("jour\n"));
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed2), jour, 248, 448);
  gtk_widget_set_size_request (jour, 80, 24);

  label23 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Priv\303\251</span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed2), label23, 464, 360);
  gtk_widget_set_size_request (label23, 49, 17);
  GTK_WIDGET_SET_FLAGS (label23, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label23), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label23), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label23), 5, 0);

  label24 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Public</span>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed2), label24, 536, 360);
  gtk_widget_set_size_request (label24, 60, 24);
  GTK_WIDGET_SET_FLAGS (label24, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label24), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label24), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label24), 5, 0);

  AjoutBoutonTypeEv = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (AjoutBoutonTypeEv);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutBoutonTypeEv, 784, 216);
  gtk_widget_set_size_request (AjoutBoutonTypeEv, 66, 29);

  AjoutPriveEv = gtk_radio_button_new_with_mnemonic (NULL, _("radiobutton3"));
  gtk_widget_show (AjoutPriveEv);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutPriveEv, 440, 360);
  gtk_widget_set_size_request (AjoutPriveEv, 24, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (AjoutPriveEv), AjoutPriveEv_group);
  AjoutPriveEv_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (AjoutPriveEv));

  AjoutPublicEv = gtk_radio_button_new_with_mnemonic (NULL, _("radiobutton4"));
  gtk_widget_show (AjoutPublicEv);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutPublicEv, 520, 352);
  gtk_widget_set_size_request (AjoutPublicEv, 16, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (AjoutPublicEv), AjoutPriveEv_group);
  AjoutPriveEv_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (AjoutPublicEv));

  AjoutTypeEv = gtk_combo_box_entry_new_text ();
  gtk_widget_show (AjoutTypeEv);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutTypeEv, 384, 208);
  gtk_widget_set_size_request (AjoutTypeEv, 341, 37);
  gtk_combo_box_append_text (GTK_COMBO_BOX (AjoutTypeEv), _("event sponsoring"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AjoutTypeEv), _("event commerciale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AjoutTypeEv), _("event sportif"));

  AjoutBoutonEv = gtk_button_new ();
  gtk_widget_show (AjoutBoutonEv);
  gtk_fixed_put (GTK_FIXED (fixed2), AjoutBoutonEv, 832, 504);
  gtk_widget_set_size_request (AjoutBoutonEv, 162, 53);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (AjoutBoutonEv), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox1), image5, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("<span foreground=\"Green\"\nsize=\"13000\" weight=\"bold\">Ajouter</span>"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox1), label41, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label41, 80, 20);
  GTK_WIDGET_SET_FLAGS (label41, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);
  gtk_label_set_justify (GTK_LABEL (label41), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label41), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label41), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label41), 5, 0);

  image15 = create_pixmap (window1, "index.gtk");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed2), image15, 1104, 80);
  gtk_widget_set_size_request (image15, 368, 232);

  AfficherAjout = gtk_button_new ();
  gtk_widget_show (AfficherAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), AfficherAjout, 1040, 512);
  gtk_widget_set_size_request (AfficherAjout, 136, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (AfficherAjout), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image17 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox11), image17, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox11), label75, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("<span foreground=\"Blue\"\nsize=\"12000\" weight=\"bold\">Ajouter un \303\251venement</span>"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label10);
  gtk_widget_set_size_request (label10, 230, 24);
  GTK_WIDGET_SET_FLAGS (label10, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label10), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label10), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label10), 5, 0);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  label28 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"13000\" weight=\"bold\">Veuiller donner l'Id de l'\303\251venement a modifier</span>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 128, 48);
  gtk_widget_set_size_request (label28, 432, 24);
  GTK_WIDGET_SET_FLAGS (label28, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);
  gtk_label_set_justify (GTK_LABEL (label28), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label28), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label28), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label28), 5, 0);

  ModifIDev = gtk_entry_new ();
  gtk_widget_show (ModifIDev);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifIDev, 584, 40);
  gtk_widget_set_size_request (ModifIDev, 360, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (ModifIDev), 8226);

  ModifNomEv = gtk_entry_new ();
  gtk_widget_show (ModifNomEv);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifNomEv, 400, 168);
  gtk_widget_set_size_request (ModifNomEv, 360, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (ModifNomEv), 8226);

  ModifNbrInvites_adj = gtk_adjustment_new (1, 0, 10000, 1, 10, 10);
  ModifNbrInvites = gtk_spin_button_new (GTK_ADJUSTMENT (ModifNbrInvites_adj), 1, 0);
  gtk_widget_show (ModifNbrInvites);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifNbrInvites, 400, 336);
  gtk_widget_set_size_request (ModifNbrInvites, 120, 32);

  label34 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Type</span>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed3), label34, 304, 256);
  gtk_widget_set_size_request (label34, 49, 17);
  GTK_WIDGET_SET_FLAGS (label34, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);
  gtk_label_set_justify (GTK_LABEL (label34), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label34), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label34), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label34), 5, 0);

  label33 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Nom</span>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed3), label33, 304, 184);
  gtk_widget_set_size_request (label33, 49, 17);
  GTK_WIDGET_SET_FLAGS (label33, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);
  gtk_label_set_justify (GTK_LABEL (label33), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label33), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label33), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label33), 5, 0);

  label35 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\"> Nombre d'invit\303\251s</span>"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed3), label35, 208, 336);
  gtk_widget_set_size_request (label35, 168, 32);
  GTK_WIDGET_SET_FLAGS (label35, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);
  gtk_label_set_justify (GTK_LABEL (label35), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label35), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label35), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label35), 5, 0);

  label36 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Priv\303\251\n</span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed3), label36, 432, 432);
  gtk_widget_set_size_request (label36, 49, 17);
  GTK_WIDGET_SET_FLAGS (label36, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);
  gtk_label_set_justify (GTK_LABEL (label36), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label36), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label36), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label36), 5, 0);

  label37 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Public</span>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed3), label37, 568, 432);
  gtk_widget_set_size_request (label37, 49, 17);
  GTK_WIDGET_SET_FLAGS (label37, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);
  gtk_label_set_justify (GTK_LABEL (label37), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label37), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label37), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label37), 4, 0);

  label38 = gtk_label_new ("");
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed3), label38, 208, 520);
  gtk_widget_set_size_request (label38, 49, 17);

  label39 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Date</span>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed3), label39, 280, 512);
  gtk_widget_set_size_request (label39, 81, 17);
  GTK_WIDGET_SET_FLAGS (label39, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);
  gtk_label_set_justify (GTK_LABEL (label39), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label39), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label39), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label39), 5, 0);

  ModifJourEv_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  ModifJourEv = gtk_spin_button_new (GTK_ADJUSTMENT (ModifJourEv_adj), 1, 0);
  gtk_widget_show (ModifJourEv);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifJourEv, 440, 512);
  gtk_widget_set_size_request (ModifJourEv, 60, 27);

  ModifMoisEv_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  ModifMoisEv = gtk_spin_button_new (GTK_ADJUSTMENT (ModifMoisEv_adj), 1, 0);
  gtk_widget_show (ModifMoisEv);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifMoisEv, 568, 512);
  gtk_widget_set_size_request (ModifMoisEv, 60, 27);

  ModifAnneeEv_adj = gtk_adjustment_new (1, 1990, 2030, 1, 10, 10);
  ModifAnneeEv = gtk_spin_button_new (GTK_ADJUSTMENT (ModifAnneeEv_adj), 1, 0);
  gtk_widget_show (ModifAnneeEv);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifAnneeEv, 728, 512);
  gtk_widget_set_size_request (ModifAnneeEv, 60, 27);

  label72 = gtk_label_new (_("Jour"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed3), label72, 392, 512);
  gtk_widget_set_size_request (label72, 49, 25);

  label73 = gtk_label_new (_("Mois\n"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed3), label73, 520, 512);
  gtk_widget_set_size_request (label73, 49, 25);

  label74 = gtk_label_new (_("Ann\303\251e\n"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed3), label74, 664, 512);
  gtk_widget_set_size_request (label74, 65, 25);

  ModifChercher = gtk_button_new_with_mnemonic (_("cherhcer"));
  gtk_widget_show (ModifChercher);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifChercher, 1000, 48);
  gtk_widget_set_size_request (ModifChercher, 74, 29);

  ModifTypeBouton = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (ModifTypeBouton);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifTypeBouton, 688, 240);
  gtk_widget_set_size_request (ModifTypeBouton, 66, 29);

  ModifPriveEv = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (ModifPriveEv);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifPriveEv, 400, 432);
  gtk_widget_set_size_request (ModifPriveEv, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ModifPriveEv), ModifPriveEv_group);
  ModifPriveEv_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ModifPriveEv));

  ModifPublicEv = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (ModifPublicEv);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifPublicEv, 544, 432);
  gtk_widget_set_size_request (ModifPublicEv, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ModifPublicEv), ModifPriveEv_group);
  ModifPriveEv_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ModifPublicEv));

  ModifBouton_ = gtk_button_new ();
  gtk_widget_show (ModifBouton_);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifBouton_, 1080, 432);
  gtk_widget_set_size_request (ModifBouton_, 224, 53);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ModifBouton_), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox2), image6, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("<span foreground=\"Blue\"\nsize=\"13000\" weight=\"bold\">Modifier</span>"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox2), label40, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label40, 80, 25);
  GTK_WIDGET_SET_FLAGS (label40, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);
  gtk_label_set_justify (GTK_LABEL (label40), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label40), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label40), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label40), 5, 0);

  ModifTypeEv = gtk_combo_box_entry_new_text ();
  gtk_widget_show (ModifTypeEv);
  gtk_fixed_put (GTK_FIXED (fixed3), ModifTypeEv, 400, 240);
  gtk_widget_set_size_request (ModifTypeEv, 253, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ModifTypeEv), _("event sponsoring "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ModifTypeEv), _("event commerciale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ModifTypeEv), _("event sportif"));

  label11 = gtk_label_new_with_mnemonic (_("<span foreground=\"Blue\"\nsize=\"12000\" weight=\"bold\">Modifier un \303\251venement </span>"));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label11);
  gtk_widget_set_size_request (label11, 230, 24);
  GTK_WIDGET_SET_FLAGS (label11, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label11), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label11), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label11), 5, 0);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  label42 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"13000\" weight=\"bold\">Veuiller donner l'ID de l'\303\251venement a supprimer</span>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed4), label42, 104, 80);
  gtk_widget_set_size_request (label42, 464, 32);
  GTK_WIDGET_SET_FLAGS (label42, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);
  gtk_label_set_justify (GTK_LABEL (label42), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label42), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label42), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label42), 5, 0);

  label43 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"13000\" >\303\251venement annul\303\251 ?</span>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed4), label43, 320, 176);
  gtk_widget_set_size_request (label43, 256, 16);
  GTK_WIDGET_SET_FLAGS (label43, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);
  gtk_label_set_justify (GTK_LABEL (label43), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label43), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label43), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label43), 5, 0);

  SuppDecrireEv = gtk_entry_new ();
  gtk_widget_show (SuppDecrireEv);
  gtk_fixed_put (GTK_FIXED (fixed4), SuppDecrireEv, 592, 280);
  gtk_widget_set_size_request (SuppDecrireEv, 480, 208);
  gtk_entry_set_invisible_char (GTK_ENTRY (SuppDecrireEv), 8226);

  label44 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\">D\303\251ccrire la raison de la suppression : </span>"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed4), label44, 256, 296);
  gtk_widget_set_size_request (label44, 296, 32);
  GTK_WIDGET_SET_FLAGS (label44, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);
  gtk_label_set_justify (GTK_LABEL (label44), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label44), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label44), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label44), 5, 0);

  SuppIDev = gtk_entry_new ();
  gtk_widget_show (SuppIDev);
  gtk_fixed_put (GTK_FIXED (fixed4), SuppIDev, 600, 80);
  gtk_widget_set_size_request (SuppIDev, 280, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (SuppIDev), 8226);

  SuppCheckboxEv = gtk_check_button_new_with_mnemonic (_("Oui\n"));
  gtk_widget_show (SuppCheckboxEv);
  gtk_fixed_put (GTK_FIXED (fixed4), SuppCheckboxEv, 608, 176);
  gtk_widget_set_size_request (SuppCheckboxEv, 118, 24);

  SuppButton = gtk_button_new ();
  gtk_widget_show (SuppButton);
  gtk_fixed_put (GTK_FIXED (fixed4), SuppButton, 1048, 88);
  gtk_widget_set_size_request (SuppButton, 104, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (SuppButton), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image18 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox12), image18, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox12), label76, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("<span foreground=\"Blue\"\nsize=\"12000\" weight=\"bold\">Supprimer un \303\251venement</span>"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label12);
  gtk_widget_set_size_request (label12, 230, 24);
  GTK_WIDGET_SET_FLAGS (label12, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label12), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label12), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label12), 5, 0);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  label46 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"13000\" weight=\"bold\">Donner l'ID de l'\303\251venemet a cherhcer</span>"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed5), label46, 224, 48);
  gtk_widget_set_size_request (label46, 400, 48);
  GTK_WIDGET_SET_FLAGS (label46, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);
  gtk_label_set_justify (GTK_LABEL (label46), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label46), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label46), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label46), 5, 0);

  IDrecherche = gtk_entry_new ();
  gtk_widget_show (IDrecherche);
  gtk_fixed_put (GTK_FIXED (fixed5), IDrecherche, 584, 48);
  gtk_widget_set_size_request (IDrecherche, 648, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (IDrecherche), 8226);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview, 336, 120);
  gtk_widget_set_size_request (treeview, 1032, 256);

  Rechercher = gtk_button_new ();
  gtk_widget_show (Rechercher);
  gtk_fixed_put (GTK_FIXED (fixed5), Rechercher, 1288, 48);
  gtk_widget_set_size_request (Rechercher, 168, 48);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Rechercher), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image8 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox4), image8, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Rchercher</span>"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox4), label47, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label47, 80, 20);
  GTK_WIDGET_SET_FLAGS (label47, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);
  gtk_label_set_justify (GTK_LABEL (label47), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label47), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label47), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label47), 5, 0);

  supprimerRecherche = gtk_button_new ();
  gtk_widget_show (supprimerRecherche);
  gtk_fixed_put (GTK_FIXED (fixed5), supprimerRecherche, 816, 400);
  gtk_widget_set_size_request (supprimerRecherche, 168, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (supprimerRecherche), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox6), image10, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("<span foreground=\"Red\"\nsize=\"13000\" weight=\"bold\">Supprimer</span>"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox6), label55, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label55, 90, 20);
  GTK_WIDGET_SET_FLAGS (label55, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);
  gtk_label_set_justify (GTK_LABEL (label55), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label55), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label55), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label55), 5, 0);

  ActualiserRecherhce = gtk_button_new ();
  gtk_widget_show (ActualiserRecherhce);
  gtk_fixed_put (GTK_FIXED (fixed5), ActualiserRecherhce, 624, 400);
  gtk_widget_set_size_request (ActualiserRecherhce, 160, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ActualiserRecherhce), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image9 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox5), image9, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("<span foreground=\"Green\"\nsize=\"13000\" weight=\"bold\">actualiser</span>"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox5), label54, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label54, 80, 20);
  GTK_WIDGET_SET_FLAGS (label54, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);
  gtk_label_set_justify (GTK_LABEL (label54), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label54), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label54), 0.5, 0.43);
  gtk_label_set_width_chars (GTK_LABEL (label54), 45);

  label13 = gtk_label_new_with_mnemonic (_("<span foreground=\"Blue\"\nsize=\"12000\" weight=\"bold\">Recherhcer un \303\251venement</span>"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label13);
  gtk_widget_set_size_request (label13, 230, 24);
  GTK_WIDGET_SET_FLAGS (label13, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label13), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label13), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label13), 5, 0);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  IDinscri = gtk_entry_new ();
  gtk_widget_show (IDinscri);
  gtk_fixed_put (GTK_FIXED (fixed6), IDinscri, 536, 112);
  gtk_widget_set_size_request (IDinscri, 312, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (IDinscri), 8226);

  nomprenomInscri = gtk_entry_new ();
  gtk_widget_show (nomprenomInscri);
  gtk_fixed_put (GTK_FIXED (fixed6), nomprenomInscri, 536, 200);
  gtk_widget_set_size_request (nomprenomInscri, 312, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomprenomInscri), 8226);

  label57 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"13000\" weight=\"bold\">Donner votre ID</span>"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed6), label57, 272, 128);
  gtk_widget_set_size_request (label57, 264, 32);
  GTK_WIDGET_SET_FLAGS (label57, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);
  gtk_label_set_justify (GTK_LABEL (label57), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label57), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label57), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label57), 5, 0);

  label58 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Nom et pr\303\251nom</span>"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed6), label58, 320, 200);
  gtk_widget_set_size_request (label58, 153, 33);
  GTK_WIDGET_SET_FLAGS (label58, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);
  gtk_label_set_justify (GTK_LABEL (label58), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label58), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label58), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label58), 5, 0);

  AgeInscri_adj = gtk_adjustment_new (0, 1, 50, 1, 10, 10);
  AgeInscri = gtk_spin_button_new (GTK_ADJUSTMENT (AgeInscri_adj), 1, 0);
  gtk_widget_show (AgeInscri);
  gtk_fixed_put (GTK_FIXED (fixed6), AgeInscri, 536, 280);
  gtk_widget_set_size_request (AgeInscri, 60, 27);

  label59 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Age</span>"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed6), label59, 376, 280);
  gtk_widget_set_size_request (label59, 49, 17);
  GTK_WIDGET_SET_FLAGS (label59, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label59), TRUE);
  gtk_label_set_justify (GTK_LABEL (label59), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label59), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label59), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label59), 5, 0);

  label60 = gtk_label_new_with_mnemonic (_("<span foreground=\"Red\"\nsize=\"18000\" weight=\"bold\">Bienvenue</span>"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed6), label60, 696, 32);
  gtk_widget_set_size_request (label60, 416, 72);
  GTK_WIDGET_SET_FLAGS (label60, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label60), TRUE);
  gtk_label_set_justify (GTK_LABEL (label60), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label60), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label60), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label60), 5, 0);

  label62 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Choisir l'\303\251venement a s'inscrire :</span>"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed6), label62, 256, 424);
  gtk_widget_set_size_request (label62, 256, 32);
  GTK_WIDGET_SET_FLAGS (label62, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label62), TRUE);
  gtk_label_set_justify (GTK_LABEL (label62), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label62), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label62), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label62), 5, 0);

  label63 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">Genre</span>"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed6), label63, 376, 368);
  gtk_widget_set_size_request (label63, 49, 17);
  GTK_WIDGET_SET_FLAGS (label63, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label63), TRUE);
  gtk_label_set_justify (GTK_LABEL (label63), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label63), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label63), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label63), 5, 0);

  image16 = create_pixmap (window1, "images2.gtk");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed6), image16, 1184, 104);
  gtk_widget_set_size_request (image16, 304, 288);

  Evenementinscrire = gtk_combo_box_entry_new_text ();
  gtk_widget_show (Evenementinscrire);
  gtk_fixed_put (GTK_FIXED (fixed6), Evenementinscrire, 528, 424);
  gtk_widget_set_size_request (Evenementinscrire, 333, 37);

  FemmeInscri = gtk_check_button_new_with_mnemonic (_("Femme\n"));
  gtk_widget_show (FemmeInscri);
  gtk_fixed_put (GTK_FIXED (fixed6), FemmeInscri, 720, 368);
  gtk_widget_set_size_request (FemmeInscri, 118, 24);

  SinscrireButton = gtk_button_new ();
  gtk_widget_show (SinscrireButton);
  gtk_fixed_put (GTK_FIXED (fixed6), SinscrireButton, 760, 520);
  gtk_widget_set_size_request (SinscrireButton, 144, 45);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (SinscrireButton), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"11000\" weight=\"bold\">S'inscrire</span>"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox8), label64, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label64, 80, 20);
  GTK_WIDGET_SET_FLAGS (label64, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label64), TRUE);
  gtk_label_set_justify (GTK_LABEL (label64), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label64), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label64), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label64), 5, 0);

  okChoisirEventInscri = gtk_button_new_with_mnemonic (_("chercher"));
  gtk_widget_show (okChoisirEventInscri);
  gtk_fixed_put (GTK_FIXED (fixed6), okChoisirEventInscri, 920, 424);
  gtk_widget_set_size_request (okChoisirEventInscri, 74, 37);

  HommeInscri = gtk_check_button_new_with_mnemonic (_("Homme"));
  gtk_widget_show (HommeInscri);
  gtk_fixed_put (GTK_FIXED (fixed6), HommeInscri, 536, 368);
  gtk_widget_set_size_request (HommeInscri, 118, 24);

  label14 = gtk_label_new_with_mnemonic (_("<span foreground=\"Blue\"\nsize=\"12000\" weight=\"bold\">S'inscrire a un \303\251venement </span>"));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label14);
  gtk_widget_set_size_request (label14, 230, 24);
  GTK_WIDGET_SET_FLAGS (label14, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label14), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label14), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label14), 5, 0);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  StatNombreEvent = gtk_entry_new ();
  gtk_widget_show (StatNombreEvent);
  gtk_fixed_put (GTK_FIXED (fixed7), StatNombreEvent, 680, 120);
  gtk_widget_set_size_request (StatNombreEvent, 392, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (StatNombreEvent), 8226);

  label65 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"16000\" >Nombre totale des \303\251venements</span>"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed7), label65, 320, 112);
  gtk_widget_set_size_request (label65, 344, 72);
  GTK_WIDGET_SET_FLAGS (label65, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);
  gtk_label_set_justify (GTK_LABEL (label65), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label65), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label65), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label65), 5, 0);

  label66 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\"\nsize=\"16000\" >Nombre totale des invit\303\251s</span>"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed7), label66, 304, 200);
  gtk_widget_set_size_request (label66, 320, 40);
  GTK_WIDGET_SET_FLAGS (label66, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);
  gtk_label_set_justify (GTK_LABEL (label66), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label66), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label66), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label66), 5, 0);

  StatNombreInvite = gtk_entry_new ();
  gtk_widget_show (StatNombreInvite);
  gtk_fixed_put (GTK_FIXED (fixed7), StatNombreInvite, 680, 208);
  gtk_widget_set_size_request (StatNombreInvite, 392, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (StatNombreInvite), 8226);

  BoutonCalculer = gtk_button_new ();
  gtk_widget_show (BoutonCalculer);
  gtk_fixed_put (GTK_FIXED (fixed7), BoutonCalculer, 608, 304);
  gtk_widget_set_size_request (BoutonCalculer, 304, 45);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (BoutonCalculer), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image13 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox9), image13, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("<span foreground=\"Blue\"\nsize=\"16000\" >Calculer</span>"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox9), label67, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label67, 80, 20);
  GTK_WIDGET_SET_FLAGS (label67, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label67), TRUE);
  gtk_label_set_justify (GTK_LABEL (label67), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label67), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label67), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label67), 5, 0);

  BoutonExporter = gtk_button_new ();
  gtk_widget_show (BoutonExporter);
  gtk_fixed_put (GTK_FIXED (fixed7), BoutonExporter, 936, 304);
  gtk_widget_set_size_request (BoutonExporter, 240, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (BoutonExporter), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image14 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox10), image14, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("<span foreground=\"Green\"\nsize=\"16000\" >Exporter</span>"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox10), label68, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label68, 90, 20);
  GTK_WIDGET_SET_FLAGS (label68, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label68), TRUE);
  gtk_label_set_justify (GTK_LABEL (label68), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label68), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label68), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label68), 5, 0);

  label15 = gtk_label_new_with_mnemonic (_("<span foreground=\"Blue\"\nsize=\"12000\" weight=\"bold\">Statistiques des \303\251venements</span>"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label15);
  gtk_widget_set_size_request (label15, 230, 24);
  GTK_WIDGET_SET_FLAGS (label15, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label15), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label15), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label15), 5, 0);

  image2 = create_pixmap (window1, "Black and White Minimalist Illustration Iron Gym Logo.png");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed1), image2, 544, 0);
  gtk_widget_set_size_request (image2, 648, 112);

  g_signal_connect ((gpointer) AjoutBoutonTypeEv, "clicked",
                    G_CALLBACK (on_AjoutBoutonTypeEv_clicked),
                    NULL);
  g_signal_connect ((gpointer) AjoutPriveEv, "toggled",
                    G_CALLBACK (on_AjoutPriv__Ev_toggled),
                    NULL);
  g_signal_connect ((gpointer) AjoutPublicEv, "toggled",
                    G_CALLBACK (on_AjoutPublicEv_toggled),
                    NULL);
  g_signal_connect ((gpointer) AjoutBoutonEv, "clicked",
                    G_CALLBACK (on_AjoutBoutonEv_clicked),
                    NULL);
  g_signal_connect ((gpointer) AfficherAjout, "clicked",
                    G_CALLBACK (on_AfficherAjout_clicked),
                    NULL);
  g_signal_connect ((gpointer) ModifChercher, "clicked",
                    G_CALLBACK (on_ModifChercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) ModifTypeBouton, "clicked",
                    G_CALLBACK (on_ModifTypeBouton_clicked),
                    NULL);
  g_signal_connect ((gpointer) ModifPriveEv, "toggled",
                    G_CALLBACK (on_ModifPriv__Ev_toggled),
                    NULL);
  g_signal_connect ((gpointer) ModifPublicEv, "toggled",
                    G_CALLBACK (on_ModifPublicEv_toggled),
                    NULL);
  g_signal_connect ((gpointer) ModifBouton_, "clicked",
                    G_CALLBACK (on_ModifBouton__clicked),
                    NULL);
  g_signal_connect ((gpointer) SuppCheckboxEv, "toggled",
                    G_CALLBACK (on_SuppCheckboxEv_toggled),
                    NULL);
  g_signal_connect ((gpointer) SuppButton, "clicked",
                    G_CALLBACK (on_SuppButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) Rechercher, "clicked",
                    G_CALLBACK (on_Rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimerRecherche, "clicked",
                    G_CALLBACK (on_supprimerRecherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) ActualiserRecherhce, "clicked",
                    G_CALLBACK (on_ActualiserRecherhce_clicked),
                    NULL);
  g_signal_connect ((gpointer) FemmeInscri, "toggled",
                    G_CALLBACK (on_FemmeInscri_toggled),
                    NULL);
  g_signal_connect ((gpointer) SinscrireButton, "clicked",
                    G_CALLBACK (on_SinscrireButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) okChoisirEventInscri, "clicked",
                    G_CALLBACK (on_okChoisirEventInscri_clicked),
                    NULL);
  g_signal_connect ((gpointer) HommeInscri, "toggled",
                    G_CALLBACK (on_HommeInscri_toggled),
                    NULL);
  g_signal_connect ((gpointer) BoutonCalculer, "clicked",
                    G_CALLBACK (on_BoutonCalculer_clicked),
                    NULL);
  g_signal_connect ((gpointer) BoutonExporter, "clicked",
                    G_CALLBACK (on_BoutonExporter_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label20), AjoutBoutonTypeEv);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label23), label24);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label28), ModifChercher);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label35), ModifNbrInvites);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label36), ModifPublicEv);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label37), ModifBouton_);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label42), SuppIDev);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label43), SuppCheckboxEv);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label46), IDrecherche);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label58), nomprenomInscri);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label59), AgeInscri);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label63), HommeInscri);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, AjoutIDev, "AjoutIDev");
  GLADE_HOOKUP_OBJECT (window1, AjoutNomEv, "AjoutNomEv");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");
  GLADE_HOOKUP_OBJECT (window1, AjoutNbrInviteEv, "AjoutNbrInviteEv");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window1, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, AjoutJourEv, "AjoutJourEv");
  GLADE_HOOKUP_OBJECT (window1, AjoutMoisEv, "AjoutMoisEv");
  GLADE_HOOKUP_OBJECT (window1, AjoutAnneeEv, "AjoutAnneeEv");
  GLADE_HOOKUP_OBJECT (window1, lab, "lab");
  GLADE_HOOKUP_OBJECT (window1, label71, "label71");
  GLADE_HOOKUP_OBJECT (window1, jour, "jour");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, AjoutBoutonTypeEv, "AjoutBoutonTypeEv");
  GLADE_HOOKUP_OBJECT (window1, AjoutPriveEv, "AjoutPriveEv");
  GLADE_HOOKUP_OBJECT (window1, AjoutPublicEv, "AjoutPublicEv");
  GLADE_HOOKUP_OBJECT (window1, AjoutTypeEv, "AjoutTypeEv");
  GLADE_HOOKUP_OBJECT (window1, AjoutBoutonEv, "AjoutBoutonEv");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, label41, "label41");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, AfficherAjout, "AfficherAjout");
  GLADE_HOOKUP_OBJECT (window1, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, label75, "label75");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, ModifIDev, "ModifIDev");
  GLADE_HOOKUP_OBJECT (window1, ModifNomEv, "ModifNomEv");
  GLADE_HOOKUP_OBJECT (window1, ModifNbrInvites, "ModifNbrInvites");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, label39, "label39");
  GLADE_HOOKUP_OBJECT (window1, ModifJourEv, "ModifJourEv");
  GLADE_HOOKUP_OBJECT (window1, ModifMoisEv, "ModifMoisEv");
  GLADE_HOOKUP_OBJECT (window1, ModifAnneeEv, "ModifAnneeEv");
  GLADE_HOOKUP_OBJECT (window1, label72, "label72");
  GLADE_HOOKUP_OBJECT (window1, label73, "label73");
  GLADE_HOOKUP_OBJECT (window1, label74, "label74");
  GLADE_HOOKUP_OBJECT (window1, ModifChercher, "ModifChercher");
  GLADE_HOOKUP_OBJECT (window1, ModifTypeBouton, "ModifTypeBouton");
  GLADE_HOOKUP_OBJECT (window1, ModifPriveEv, "ModifPriveEv");
  GLADE_HOOKUP_OBJECT (window1, ModifPublicEv, "ModifPublicEv");
  GLADE_HOOKUP_OBJECT (window1, ModifBouton_, "ModifBouton_");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1, label40, "label40");
  GLADE_HOOKUP_OBJECT (window1, ModifTypeEv, "ModifTypeEv");
  GLADE_HOOKUP_OBJECT (window1, label11, "label11");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, label42, "label42");
  GLADE_HOOKUP_OBJECT (window1, label43, "label43");
  GLADE_HOOKUP_OBJECT (window1, SuppDecrireEv, "SuppDecrireEv");
  GLADE_HOOKUP_OBJECT (window1, label44, "label44");
  GLADE_HOOKUP_OBJECT (window1, SuppIDev, "SuppIDev");
  GLADE_HOOKUP_OBJECT (window1, SuppCheckboxEv, "SuppCheckboxEv");
  GLADE_HOOKUP_OBJECT (window1, SuppButton, "SuppButton");
  GLADE_HOOKUP_OBJECT (window1, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image18, "image18");
  GLADE_HOOKUP_OBJECT (window1, label76, "label76");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, label46, "label46");
  GLADE_HOOKUP_OBJECT (window1, IDrecherche, "IDrecherche");
  GLADE_HOOKUP_OBJECT (window1, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (window1, Rechercher, "Rechercher");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, label47, "label47");
  GLADE_HOOKUP_OBJECT (window1, supprimerRecherche, "supprimerRecherche");
  GLADE_HOOKUP_OBJECT (window1, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, label55, "label55");
  GLADE_HOOKUP_OBJECT (window1, ActualiserRecherhce, "ActualiserRecherhce");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, label54, "label54");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, IDinscri, "IDinscri");
  GLADE_HOOKUP_OBJECT (window1, nomprenomInscri, "nomprenomInscri");
  GLADE_HOOKUP_OBJECT (window1, label57, "label57");
  GLADE_HOOKUP_OBJECT (window1, label58, "label58");
  GLADE_HOOKUP_OBJECT (window1, AgeInscri, "AgeInscri");
  GLADE_HOOKUP_OBJECT (window1, label59, "label59");
  GLADE_HOOKUP_OBJECT (window1, label60, "label60");
  GLADE_HOOKUP_OBJECT (window1, label62, "label62");
  GLADE_HOOKUP_OBJECT (window1, label63, "label63");
  GLADE_HOOKUP_OBJECT (window1, image16, "image16");
  GLADE_HOOKUP_OBJECT (window1, Evenementinscrire, "Evenementinscrire");
  GLADE_HOOKUP_OBJECT (window1, FemmeInscri, "FemmeInscri");
  GLADE_HOOKUP_OBJECT (window1, SinscrireButton, "SinscrireButton");
  GLADE_HOOKUP_OBJECT (window1, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, image12, "image12");
  GLADE_HOOKUP_OBJECT (window1, label64, "label64");
  GLADE_HOOKUP_OBJECT (window1, okChoisirEventInscri, "okChoisirEventInscri");
  GLADE_HOOKUP_OBJECT (window1, HommeInscri, "HommeInscri");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window1, StatNombreEvent, "StatNombreEvent");
  GLADE_HOOKUP_OBJECT (window1, label65, "label65");
  GLADE_HOOKUP_OBJECT (window1, label66, "label66");
  GLADE_HOOKUP_OBJECT (window1, StatNombreInvite, "StatNombreInvite");
  GLADE_HOOKUP_OBJECT (window1, BoutonCalculer, "BoutonCalculer");
  GLADE_HOOKUP_OBJECT (window1, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, label67, "label67");
  GLADE_HOOKUP_OBJECT (window1, BoutonExporter, "BoutonExporter");
  GLADE_HOOKUP_OBJECT (window1, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label68, "label68");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");

  return window1;
}

