/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_des_cours (void)
{
  GtkWidget *gestion_des_cours;
  GtkWidget *alignment1;
  GtkWidget *vbox1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *fixed14;
  GtkWidget *image7;
  GtkWidget *label55;
  GtkWidget *image8;
  GtkWidget *image5;
  GtkWidget *label54;
  GtkWidget *image12;
  GtkWidget *image11;
  GtkWidget *notebook1;
  GtkWidget *fixed7;
  GtkWidget *entry_id;
  GtkWidget *entry_nom;
  GtkWidget *entry_coach;
  GtkWidget *entry_jour;
  GtkWidget *entry_heure;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkObject *spin_places_adj;
  GtkWidget *spin_places;
  GtkWidget *button_ajouter;
  GtkWidget *alignment2;
  GtkWidget *hbox1;
  GtkWidget *image9;
  GtkWidget *label56;
  GtkWidget *label19;
  GtkWidget *button_modifier;
  GtkWidget *image14;
  GtkWidget *label12;
  GtkWidget *fixed11;
  GtkWidget *label57;
  GtkWidget *treeview_cours;
  GtkWidget *entry_id_rechercher;
  GtkWidget *label61;
  GtkWidget *label63;
  GtkWidget *entry_id_supprimer;
  GtkWidget *label64;
  GtkWidget *label60;
  GtkWidget *button_supprimer;
  GtkWidget *button_rechercher;
  GtkWidget *label59;
  GtkWidget *label16;
  GtkWidget *fixed13;
  GtkWidget *entry_id_inscrire;
  GtkWidget *image3;
  GtkWidget *label43;
  GtkWidget *label65;
  GtkWidget *comboboxentry1;
  GtkWidget *button_inscrire;
  GtkWidget *button_desinscrire;
  GtkObject *spin_inscription_adj;
  GtkWidget *spin_inscription;
  GtkWidget *radio_par_id;
  GSList *radio_par_id_group = NULL;
  GtkWidget *radio_par_cours;
  GtkWidget *image15;
  GtkWidget *label17;
  GtkWidget *fixed12;
  GtkWidget *entry_nombre_total;
  GtkWidget *entry_cours_actif;
  GtkWidget *label33;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *button_calculer;
  GtkWidget *alignment3;
  GtkWidget *hbox2;
  GtkWidget *image13;
  GtkWidget *label58;
  GtkWidget *image16;
  GtkWidget *label18;

  gestion_des_cours = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_des_cours), _("Gestion des cours-Salle de sport"));

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (gestion_des_cours), alignment1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), vbox1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, FALSE, FALSE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);
  gtk_widget_set_size_request (viewport1, 1130, 110);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed14);
  gtk_widget_set_size_request (fixed14, 1128, 200);

  image7 = gtk_image_new_from_stock ("gtk-bold", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed14), image7, 224, 32);
  gtk_widget_set_size_request (image7, 24, 24);

  label55 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>+216 7364189</b></span>"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed14), label55, 248, 64);
  gtk_widget_set_size_request (label55, 112, 16);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  image8 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed14), image8, 224, 64);
  gtk_widget_set_size_request (image8, 21, 21);

  image5 = create_pixmap (gestion_des_cours, "images.gtk");
  gtk_widget_show (image5);
  gtk_fixed_put (GTK_FIXED (fixed14), image5, 1224, 0);
  gtk_widget_set_size_request (image5, 264, 112);

  label54 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>Ironcore1570@gmail.com</b></span>\n"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed14), label54, 256, 32);
  gtk_widget_set_size_request (label54, 192, 16);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  image12 = create_pixmap (gestion_des_cours, "images.gtk");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed14), image12, 960, 0);
  gtk_widget_set_size_request (image12, 312, 104);

  image11 = create_pixmap (gestion_des_cours, "Black and White Minimalist Illustration Iron Gym Logo.gtk");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed14), image11, 536, 0);
  gtk_widget_set_size_request (image11, 248, 104);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_id, 632, 72);
  gtk_widget_set_size_request (entry_id, 296, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_nom, 632, 136);
  gtk_widget_set_size_request (entry_nom, 296, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_coach = gtk_entry_new ();
  gtk_widget_show (entry_coach);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_coach, 632, 200);
  gtk_widget_set_size_request (entry_coach, 296, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_coach), 8226);

  entry_jour = gtk_entry_new ();
  gtk_widget_show (entry_jour);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_jour, 632, 272);
  gtk_widget_set_size_request (entry_jour, 296, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_jour), 8226);

  entry_heure = gtk_entry_new ();
  gtk_widget_show (entry_heure);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_heure, 632, 344);
  gtk_widget_set_size_request (entry_heure, 296, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_heure), 8226);

  label22 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>Coach</b></span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed7), label22, 496, 200);
  gtk_widget_set_size_request (label22, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label23 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>Jour</b></span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed7), label23, 496, 272);
  gtk_widget_set_size_request (label23, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label24 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>Heure</b></span>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed7), label24, 496, 344);
  gtk_widget_set_size_request (label24, 56, 16);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>Nombre de places</b></span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed7), label25, 456, 416);
  gtk_widget_set_size_request (label25, 152, 16);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label20 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>ID </b></span>\n"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed7), label20, 456, 80);
  gtk_widget_set_size_request (label20, 120, 16);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  label21 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>Nom</b></span>\n"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed7), label21, 456, 144);
  gtk_widget_set_size_request (label21, 120, 16);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  spin_places_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_places = gtk_spin_button_new (GTK_ADJUSTMENT (spin_places_adj), 1, 0);
  gtk_widget_show (spin_places);
  gtk_fixed_put (GTK_FIXED (fixed7), spin_places, 632, 408);
  gtk_widget_set_size_request (spin_places, 296, 32);

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed7), button_ajouter, 816, 472);
  gtk_widget_set_size_request (button_ajouter, 160, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox1);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox1), image9, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\" size=\"12000\"><b>Bouton Ajouter </b></span>\n"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox1), label56, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  label19 = gtk_label_new (_("<span foreground=\"Black\" size=\"18000\"><b>Ajouter et Modifier Cours </b></span>\n"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed7), label19, 536, 24);
  gtk_widget_set_size_request (label19, 336, 40);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  button_modifier = gtk_button_new_with_mnemonic (_("Bouton Modifier"));
  gtk_widget_show (button_modifier);
  gtk_fixed_put (GTK_FIXED (fixed7), button_modifier, 616, 472);
  gtk_widget_set_size_request (button_modifier, 176, 32);

  image14 = create_pixmap (gestion_des_cours, "cardio-galerija-blue.jpg");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed7), image14, 104, 120);
  gtk_widget_set_size_request (image14, 304, 232);

  label12 = gtk_label_new (_("<span \nforeground=\"DarkBlue\"\nsize=\"13000\">Ajouter et Modifier</span>"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label12);
  gtk_widget_set_size_request (label12, 150, -1);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);

  label57 = gtk_label_new (_("<span foreground=\"Black\" size=\"18000\"><b>Liste des cours </b></span>\n"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed11), label57, 488, 56);
  gtk_widget_set_size_request (label57, 408, 56);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);

  treeview_cours = gtk_tree_view_new ();
  gtk_widget_show (treeview_cours);
  gtk_fixed_put (GTK_FIXED (fixed11), treeview_cours, 360, 104);
  gtk_widget_set_size_request (treeview_cours, 704, 376);

  entry_id_rechercher = gtk_entry_new ();
  gtk_widget_show (entry_id_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_id_rechercher, 168, 112);
  gtk_widget_set_size_request (entry_id_rechercher, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_rechercher), 8226);

  label61 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>ID \303\240 rechercher : </b></span>"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed11), label61, 16, 112);
  gtk_widget_set_size_request (label61, 144, 32);
  gtk_label_set_use_markup (GTK_LABEL (label61), TRUE);

  label63 = gtk_label_new (_("<span foreground=\"Black\" size=\"18000\"><b>Supprimer un cours</b></span>"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed11), label63, 48, 368);
  gtk_widget_set_size_request (label63, 264, 40);
  gtk_label_set_use_markup (GTK_LABEL (label63), TRUE);

  entry_id_supprimer = gtk_entry_new ();
  gtk_widget_show (entry_id_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_id_supprimer, 160, 416);
  gtk_widget_set_size_request (entry_id_supprimer, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_supprimer), 8226);

  label64 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>ID du cours : </b></span>"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed11), label64, 16, 416);
  gtk_widget_set_size_request (label64, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label64), TRUE);

  label60 = gtk_label_new (_("<span foreground=\"Black\" size=\"18000\"><b>Rechercher un cours</b></span>"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed11), label60, 16, 56);
  gtk_widget_set_size_request (label60, 336, 48);
  gtk_label_set_use_markup (GTK_LABEL (label60), TRUE);

  button_supprimer = gtk_button_new_with_mnemonic (_("Bouton Supprimer"));
  gtk_widget_show (button_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed11), button_supprimer, 160, 464);
  gtk_widget_set_size_request (button_supprimer, 184, 32);

  button_rechercher = gtk_button_new_with_mnemonic (_("Bouton Rechercher"));
  gtk_widget_show (button_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed11), button_rechercher, 168, 160);
  gtk_widget_set_size_request (button_rechercher, 176, 32);

  label59 = gtk_label_new (_("label59"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed11), label59, 16, 216);
  gtk_widget_set_size_request (label59, 328, 144);
  gtk_label_set_line_wrap (GTK_LABEL (label59), TRUE);

  label16 = gtk_label_new (_("<span \nforeground=\"DarkBlue\"\nsize=\"13000\">Afficher</span>"));
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label16);
  gtk_widget_set_size_request (label16, 150, -1);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed13);

  entry_id_inscrire = gtk_entry_new ();
  gtk_widget_show (entry_id_inscrire);
  gtk_fixed_put (GTK_FIXED (fixed13), entry_id_inscrire, 696, 120);
  gtk_widget_set_size_request (entry_id_inscrire, 296, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_inscrire), 8226);

  image3 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed13), image3, 464, 120);
  gtk_widget_set_size_request (image3, 24, 24);

  label43 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>ID cours : </b></span>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed13), label43, 488, 112);
  gtk_widget_set_size_request (label43, 192, 40);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label65 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>Nom du cours  : </b></span>"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed13), label65, 520, 168);
  gtk_widget_set_size_request (label65, 128, 32);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry1, 696, 168);
  gtk_widget_set_size_request (comboboxentry1, 301, 32);

  button_inscrire = gtk_button_new_with_mnemonic (_("Bouton inscrire"));
  gtk_widget_show (button_inscrire);
  gtk_fixed_put (GTK_FIXED (fixed13), button_inscrire, 696, 240);
  gtk_widget_set_size_request (button_inscrire, 160, 32);

  button_desinscrire = gtk_button_new_with_mnemonic (_("Bouton desinscrire"));
  gtk_widget_show (button_desinscrire);
  gtk_fixed_put (GTK_FIXED (fixed13), button_desinscrire, 696, 296);
  gtk_widget_set_size_request (button_desinscrire, 160, 32);

  spin_inscription_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spin_inscription = gtk_spin_button_new (GTK_ADJUSTMENT (spin_inscription_adj), 1, 0);
  gtk_widget_show (spin_inscription);
  gtk_fixed_put (GTK_FIXED (fixed13), spin_inscription, 880, 240);
  gtk_widget_set_size_request (spin_inscription, 56, 32);

  radio_par_id = gtk_radio_button_new_with_mnemonic (NULL, _("Par ID"));
  gtk_widget_show (radio_par_id);
  gtk_fixed_put (GTK_FIXED (fixed13), radio_par_id, 1000, 120);
  gtk_widget_set_size_request (radio_par_id, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_par_id), radio_par_id_group);
  radio_par_id_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_par_id));

  radio_par_cours = gtk_radio_button_new_with_mnemonic (NULL, _("Par Cours"));
  gtk_widget_show (radio_par_cours);
  gtk_fixed_put (GTK_FIXED (fixed13), radio_par_cours, 1000, 168);
  gtk_widget_set_size_request (radio_par_cours, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_par_cours), radio_par_id_group);
  radio_par_id_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_par_cours));

  image15 = create_pixmap (gestion_des_cours, "Untitled.jpeg");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed13), image15, 136, 152);
  gtk_widget_set_size_request (image15, 280, 184);

  label17 = gtk_label_new (_("<span \nforeground=\"DarkBlue\"\nsize=\"13000\">Inscrire</span>"));
  gtk_widget_show (label17);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label17);
  gtk_widget_set_size_request (label17, 150, -1);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12);

  entry_nombre_total = gtk_entry_new ();
  gtk_widget_show (entry_nombre_total);
  gtk_fixed_put (GTK_FIXED (fixed12), entry_nombre_total, 680, 120);
  gtk_widget_set_size_request (entry_nombre_total, 296, 32);
  gtk_editable_set_editable (GTK_EDITABLE (entry_nombre_total), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nombre_total), 8226);

  entry_cours_actif = gtk_entry_new ();
  gtk_widget_show (entry_cours_actif);
  gtk_fixed_put (GTK_FIXED (fixed12), entry_cours_actif, 680, 184);
  gtk_widget_set_size_request (entry_cours_actif, 296, 32);
  gtk_editable_set_editable (GTK_EDITABLE (entry_cours_actif), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cours_actif), 8226);

  label33 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>Nombres total des cours : </b></span>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed12), label33, 464, 120);
  gtk_widget_set_size_request (label33, 200, 32);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  label52 = gtk_label_new (_("<span foreground=\"Black\" size=\"18000\"><b>Statistique des cours</b></span>"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed12), label52, 520, 32);
  gtk_widget_set_size_request (label52, 368, 40);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  label53 = gtk_label_new (_("<span foreground=\"Black\" size=\"12000\"><b>Cours le plus actif </b></span>"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed12), label53, 456, 184);
  gtk_widget_set_size_request (label53, 160, 32);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  button_calculer = gtk_button_new ();
  gtk_widget_show (button_calculer);
  gtk_fixed_put (GTK_FIXED (fixed12), button_calculer, 840, 256);
  gtk_widget_set_size_request (button_calculer, 136, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_calculer), alignment3);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox2);

  image13 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox2), image13, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("<span foreground=\"Black\" size=\"12000\"><b>Calculer</b></span>\n"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox2), label58, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  image16 = create_pixmap (gestion_des_cours, "images_blue.jpeg");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed12), image16, 152, 96);
  gtk_widget_set_size_request (image16, 272, 184);

  label18 = gtk_label_new (_("<span \nforeground=\"DarkBlue\"\nsize=\"13000\">Statistique</span>"));
  gtk_widget_show (label18);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label18);
  gtk_widget_set_size_request (label18, 150, -1);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer, "clicked",
                    G_CALLBACK (on_button_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rechercher, "clicked",
                    G_CALLBACK (on_button_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_inscrire, "clicked",
                    G_CALLBACK (on_button_inscrire_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_desinscrire, "clicked",
                    G_CALLBACK (on_button_desinscrire_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_calculer, "clicked",
                    G_CALLBACK (on_button_calculer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_des_cours, gestion_des_cours, "gestion_des_cours");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label55, "label55");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label54, "label54");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image12, "image12");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image11, "image11");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, entry_coach, "entry_coach");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, entry_jour, "entry_jour");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, entry_heure, "entry_heure");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label22, "label22");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label23, "label23");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label24, "label24");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, spin_places, "spin_places");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label56, "label56");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, button_modifier, "button_modifier");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image14, "image14");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label12, "label12");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label57, "label57");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, treeview_cours, "treeview_cours");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, entry_id_rechercher, "entry_id_rechercher");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label61, "label61");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label63, "label63");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, entry_id_supprimer, "entry_id_supprimer");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label64, "label64");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label60, "label60");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, button_supprimer, "button_supprimer");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, button_rechercher, "button_rechercher");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label59, "label59");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, entry_id_inscrire, "entry_id_inscrire");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label43, "label43");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label65, "label65");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, button_inscrire, "button_inscrire");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, button_desinscrire, "button_desinscrire");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, spin_inscription, "spin_inscription");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, radio_par_id, "radio_par_id");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, radio_par_cours, "radio_par_cours");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image15, "image15");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, entry_nombre_total, "entry_nombre_total");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, entry_cours_actif, "entry_cours_actif");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label33, "label33");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label52, "label52");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label53, "label53");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, button_calculer, "button_calculer");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image13, "image13");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label58, "label58");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, image16, "image16");
  GLADE_HOOKUP_OBJECT (gestion_des_cours, label18, "label18");

  return gestion_des_cours;
}

